export type WordEntry = {
	english: string;
	romaji: string;
	hiragana: string;
	kanji?: string;
	partOfSpeech?: string;
	jlpt?: "N5" | "N4" | "N3" | "N2" | "N1";
	tip?: string;
	example: {
		japanese: string;
		romaji: string;
		english: string;
	};
	related?: Array<{
		japanese: string;
		romaji: string;
		english: string;
	}>;
};

export const WORDS: WordEntry[] = [
	{
		english: "Water",
		romaji: "mizu",
		hiragana: "みず",
		kanji: "水",
		partOfSpeech: "noun",
		jlpt: "N5",
		tip: "Say it short: mi-zu (not mee-zoo).",
		example: {
			japanese: "グレームとリノは水をくださいと言いました。",
			romaji: "Gureemu to Rino wa mizu o kudasai to iimashita.",
			english: "Graeme and Rino said, “Water, please.”",
		},
		related: [
			{ japanese: "お茶", romaji: "ocha", english: "tea" },
			{ japanese: "コーヒー", romaji: "koohii", english: "coffee" },
		],
	},
	{
		english: "Thank you",
		romaji: "arigatou",
		hiragana: "ありがとう",
		kanji: "有難う",
		partOfSpeech: "phrase",
		jlpt: "N5",
		tip: "Add politeness: ありがとうございます (arigatou gozaimasu).",
		example: {
			japanese: "リノが助けてくれて、グレームは「ありがとう！」と言いました。",
			romaji: "Rino ga tasukete kurete, Gureemu wa \"Arigatou!\" to iimashita.",
			english: "Rino helped, and Graeme said, “Thank you!”",
		},
		related: [
			{ japanese: "どうも", romaji: "doumo", english: "thanks / very" },
			{
				japanese: "すみません",
				romaji: "sumimasen",
				english: "excuse me / sorry",
			},
		],
	},
	{
		english: "Excuse me / sorry",
		romaji: "sumimasen",
		hiragana: "すみません",
		partOfSpeech: "phrase",
		jlpt: "N5",
		tip: "Use it to get attention, apologize, or say “thanks” lightly.",
		example: {
			japanese: "グレームは「すみません、もう一回お願いします」と言って、リノはうなずきました。",
			romaji:
				"Gureemu wa \"Sumimasen, mou ikkai onegaishimasu\" to itte, Rino wa unazukimashita.",
			english: "Graeme said, “Excuse me, one more time please,” and Rino nodded.",
		},
		related: [
			{ japanese: "お願いします", romaji: "onegaishimasu", english: "please" },
			{ japanese: "大丈夫", romaji: "daijoubu", english: "okay / all right" },
		],
	},
	{
		english: "Good morning",
		romaji: "ohayou",
		hiragana: "おはよう",
		kanji: "お早う",
		partOfSpeech: "phrase",
		jlpt: "N5",
		tip: "Polite: おはようございます (ohayou gozaimasu).",
		example: {
			japanese: "朝、リノは「おはよう！」と言って、グレームも「おはよう！」と言いました。",
			romaji:
				"Asa, Rino wa \"Ohayou!\" to itte, Gureemu mo \"Ohayou!\" to iimashita.",
			english: "In the morning, Rino said “Good morning!” and Graeme did too.",
		},
		related: [
			{
				japanese: "こんにちは",
				romaji: "konnichiwa",
				english: "hello (daytime)",
			},
			{ japanese: "こんばんは", romaji: "konbanwa", english: "good evening" },
		],
	},
	{
		english: "Delicious",
		romaji: "oishii",
		hiragana: "おいしい",
		kanji: "美味しい",
		partOfSpeech: "i-adjective",
		jlpt: "N5",
		tip: "Casual food compliment: おいしい！ (Oishii!).",
		example: {
			japanese: "横浜でラーメンを食べて、グレームとリノは「おいしい！」と言いました。",
			romaji:
				"Yokohama de raamen o tabete, Gureemu to Rino wa \"Oishii!\" to iimashita.",
			english: "Eating ramen in Yokohama, Graeme and Rino said, “Delicious!”",
		},
		related: [
			{ japanese: "好き", romaji: "suki", english: "to like" },
			{ japanese: "まずい", romaji: "mazui", english: "bad-tasting" },
		],
	},
	{
		english: "Friend",
		romaji: "tomodachi",
		hiragana: "ともだち",
		kanji: "友達",
		partOfSpeech: "noun",
		jlpt: "N5",
		tip: "Often with の: 友達の… (tomodachi no …) “my friend’s …”.",
		example: {
			japanese: "グレームとリノは友達です。",
			romaji: "Gureemu to Rino wa tomodachi desu.",
			english: "Graeme and Rino are friends.",
		},
		related: [
			{ japanese: "家族", romaji: "kazoku", english: "family" },
			{ japanese: "先生", romaji: "sensei", english: "teacher" },
		],
	},
	{
		english: "To eat",
		romaji: "taberu",
		hiragana: "たべる",
		kanji: "食べる",
		partOfSpeech: "verb",
		jlpt: "N5",
		tip: "Polite present: 食べます (tabemasu).",
		example: {
			japanese: "グレームはパンを食べて、リノはご飯を食べます。",
			romaji: "Gureemu wa pan o tabete, Rino wa gohan o tabemasu.",
			english: "Graeme eats bread, and Rino eats rice.",
		},
		related: [
			{ japanese: "飲む", romaji: "nomu", english: "to drink" },
			{ japanese: "ご飯", romaji: "gohan", english: "rice / meal" },
		],
	},
	{
		english: "Today",
		romaji: "kyou",
		hiragana: "きょう",
		kanji: "今日",
		partOfSpeech: "noun",
		jlpt: "N5",
		tip: "Paired words: 今日 / 明日 / 昨日 (today / tomorrow / yesterday).",
		example: {
			japanese: "今日は北海道に行く日だと、グレームとリノは言いました。",
			romaji: "Kyou wa Hokkaidou ni iku hi da to, Gureemu to Rino wa iimashita.",
			english: "Graeme and Rino said today is the day to go to Hokkaido.",
		},
		related: [
			{ japanese: "明日", romaji: "ashita", english: "tomorrow" },
			{ japanese: "昨日", romaji: "kinou", english: "yesterday" },
		],
	},
	{
		english: "To understand",
		romaji: "wakaru",
		hiragana: "わかる",
		kanji: "分かる",
		partOfSpeech: "verb",
		jlpt: "N5",
		tip: "Useful pair: わかります / わかりません (I understand / I don’t).",
		example: {
			japanese: "リノが説明して、グレームは「わかる！」と言いました。",
			romaji: "Rino ga setsumei shite, Gureemu wa \"Wakaru!\" to iimashita.",
			english: "Rino explained it, and Graeme said, “I get it!”",
		},
		related: [
			{ japanese: "知る", romaji: "shiru", english: "to know" },
			{ japanese: "少し", romaji: "sukoshi", english: "a little" },
		],
	},
	{
		english: "Cute",
		romaji: "kawaii",
		hiragana: "かわいい",
		kanji: "可愛い",
		partOfSpeech: "i-adjective",
		jlpt: "N5",
		tip: "Common casual reaction: かわいい！ (Kawaii!).",
		example: {
			japanese: "リノが見つけた犬を見て、グレームは「かわいい！」と言いました。",
			romaji: "Rino ga mitsuketa inu o mite, Gureemu wa \"Kawaii!\" to iimashita.",
			english: "Seeing the dog Rino found, Graeme said, “Cute!”",
		},
		related: [
			{ japanese: "犬", romaji: "inu", english: "dog" },
			{ japanese: "猫", romaji: "neko", english: "cat" },
		],
	},
	{
		english: "Yes",
		romaji: "hai",
		hiragana: "はい",
		partOfSpeech: "phrase",
		jlpt: "N5",
		tip: "For “I see / okay”: はい、わかりました (hai, wakarimashita).",
		example: {
			japanese: "リノ: はい。グレーム: よかった！",
			romaji: "Rino: Hai. Gureemu: Yokatta!",
			english: "Rino: Yes. Graeme: Great!",
		},
	},
	{
		english: "No",
		romaji: "iie",
		hiragana: "いいえ",
		partOfSpeech: "phrase",
		jlpt: "N5",
		example: {
			japanese: "グレーム: コーヒー？ リノ: いいえ、お茶。",
			romaji: "Gureemu: Koohii? Rino: Iie, ocha.",
			english: "Graeme: Coffee? Rino: No, tea.",
		},
	},
	{
		english: "Please",
		romaji: "onegaishimasu",
		hiragana: "おねがいします",
		kanji: "お願いします",
		partOfSpeech: "phrase",
		jlpt: "N5",
		tip: "万能フレーズ: “please” + “nice to meet you” vibes.",
		example: {
			japanese: "グレームは「これ、お願いします」と言って、リノは笑いました。",
			romaji: "Gureemu wa \"Kore, onegaishimasu\" to itte, Rino wa waraimashita.",
			english: "Graeme said, “This one, please,” and Rino laughed.",
		},
	},
	{
		english: "Hello (daytime)",
		romaji: "konnichiwa",
		hiragana: "こんにちは",
		partOfSpeech: "phrase",
		jlpt: "N5",
		example: {
			japanese: "横浜で会って、リノは「こんにちは」、グレームも「こんにちは」と言いました。",
			romaji:
				"Yokohama de atte, Rino wa \"Konnichiwa\", Gureemu mo \"Konnichiwa\" to iimashita.",
			english: "Meeting in Yokohama, Rino said “Hello,” and Graeme did too.",
		},
	},
	{
		english: "Good evening",
		romaji: "konbanwa",
		hiragana: "こんばんは",
		partOfSpeech: "phrase",
		jlpt: "N5",
		example: {
			japanese: "夜、リノは「こんばんは」と言って、グレームは手をふりました。",
			romaji: "Yoru, Rino wa \"Konbanwa\" to itte, Gureemu wa te o furimashita.",
			english: "At night, Rino said “Good evening,” and Graeme waved.",
		},
	},
	{
		english: "Good night",
		romaji: "oyasumi",
		hiragana: "おやすみ",
		partOfSpeech: "phrase",
		jlpt: "N5",
		tip: "Polite: おやすみなさい (oyasuminasai).",
		example: {
			japanese: "グレームは「おやすみ」と言って、リノも「おやすみ」と言いました。",
			romaji: "Gureemu wa \"Oyasumi\" to itte, Rino mo \"Oyasumi\" to iimashita.",
			english: "Graeme said “Good night,” and Rino said it too.",
		},
	},
	{
		english: "Goodbye",
		romaji: "sayounara",
		hiragana: "さようなら",
		partOfSpeech: "phrase",
		jlpt: "N5",
		example: {
			japanese: "駅で別れて、リノは「さようなら」、グレームは「またね」と言いました。",
			romaji:
				"Eki de wakarete, Rino wa \"Sayounara\", Gureemu wa \"Matane\" to iimashita.",
			english: "Parting at the station, Rino said “Goodbye,” and Graeme said “See you.”",
		},
	},
	{
		english: "Okay / all right",
		romaji: "daijoubu",
		hiragana: "だいじょうぶ",
		kanji: "大丈夫",
		partOfSpeech: "na-adjective",
		jlpt: "N5",
		example: {
			japanese: "グレームが転んで、リノは「大丈夫？」と聞きました。",
			romaji: "Gureemu ga koronde, Rino wa \"Daijoubu?\" to kikimashita.",
			english: "Graeme fell, and Rino asked, “Are you okay?”",
		},
	},
	{
		english: "How much?",
		romaji: "ikura",
		hiragana: "いくら",
		partOfSpeech: "question",
		jlpt: "N5",
		example: {
			japanese: "グレームは「これ、いくらですか」と聞いて、リノは答えました。",
			romaji: "Gureemu wa \"Kore, ikura desu ka\" to kiite, Rino wa kotaemashita.",
			english: "Graeme asked “How much is this?” and Rino answered.",
		},
	},
	{
		english: "Where?",
		romaji: "doko",
		hiragana: "どこ",
		partOfSpeech: "question",
		jlpt: "N5",
		example: {
			japanese: "グレームは「トイレはどこですか」と聞いて、リノは指さしました。",
			romaji: "Gureemu wa \"Toire wa doko desu ka\" to kiite, Rino wa yubisashimashita.",
			english: "Graeme asked “Where is the bathroom?” and Rino pointed.",
		},
	},
	{
		english: "What?",
		romaji: "nani",
		hiragana: "なに",
		kanji: "何",
		partOfSpeech: "question",
		jlpt: "N5",
		example: {
			japanese: "リノが笑って、グレームは「なに？」と聞きました。",
			romaji: "Rino ga waratte, Gureemu wa \"Nani?\" to kikimashita.",
			english: "Rino laughed, and Graeme asked, “What?”",
		},
	},
	{
		english: "Who?",
		romaji: "dare",
		hiragana: "だれ",
		kanji: "誰",
		partOfSpeech: "question",
		jlpt: "N5",
		example: {
			japanese: "グレームは「だれ？」と聞いて、リノは「わたし！」と言いました。",
			romaji: "Gureemu wa \"Dare?\" to kiite, Rino wa \"Watashi!\" to iimashita.",
			english: "Graeme asked “Who?” and Rino said, “Me!”",
		},
	},
	{
		english: "When?",
		romaji: "itsu",
		hiragana: "いつ",
		partOfSpeech: "question",
		jlpt: "N5",
		example: {
			japanese: "グレームは「いつ行く？」と聞いて、リノは「明日」と言いました。",
			romaji: "Gureemu wa \"Itsu iku?\" to kiite, Rino wa \"Ashita\" to iimashita.",
			english: "Graeme asked “When are we going?” and Rino said “Tomorrow.”",
		},
	},
	{
		english: "Why?",
		romaji: "doushite",
		hiragana: "どうして",
		partOfSpeech: "question",
		jlpt: "N5",
		example: {
			japanese: "リノが急いでいて、グレームは「どうして？」と聞きました。",
			romaji: "Rino ga isoide ite, Gureemu wa \"Doushite?\" to kikimashita.",
			english: "Rino was rushing, and Graeme asked, “Why?”",
		},
	},
	{
		english: "How? / what way?",
		romaji: "dou",
		hiragana: "どう",
		partOfSpeech: "question",
		jlpt: "N5",
		example: {
			japanese: "グレームは「どうする？」と聞いて、リノは「コーヒーを飲む」と言いました。",
			romaji: "Gureemu wa \"Dou suru?\" to kiite, Rino wa \"Koohii o nomu\" to iimashita.",
			english: "Graeme asked “What should we do?” and Rino said “Drink coffee.”",
		},
	},
	{
		english: "This",
		romaji: "kore",
		hiragana: "これ",
		partOfSpeech: "pronoun",
		jlpt: "N5",
		example: {
			japanese: "グレームは「これがいい」と言って、リノはうなずきました。",
			romaji: "Gureemu wa \"Kore ga ii\" to itte, Rino wa unazukimashita.",
			english: "Graeme said “This one is good,” and Rino nodded.",
		},
	},
	{
		english: "That",
		romaji: "sore",
		hiragana: "それ",
		partOfSpeech: "pronoun",
		jlpt: "N5",
		example: {
			japanese: "リノは「それはダメ」と言って、グレームは笑いました。",
			romaji: "Rino wa \"Sore wa dame\" to itte, Gureemu wa waraimashita.",
			english: "Rino said “That one’s no good,” and Graeme laughed.",
		},
	},
	{
		english: "That (over there)",
		romaji: "are",
		hiragana: "あれ",
		partOfSpeech: "pronoun",
		jlpt: "N5",
		example: {
			japanese: "グレームは「あれは何？」と聞いて、リノは「猫だよ」と答えました。",
			romaji: "Gureemu wa \"Are wa nani?\" to kiite, Rino wa \"Neko da yo\" to kotaemashita.",
			english: "Graeme asked “What’s that over there?” and Rino said “A cat.”",
		},
	},
	{
		english: "Which one?",
		romaji: "dore",
		hiragana: "どれ",
		partOfSpeech: "question",
		jlpt: "N5",
		example: {
			japanese: "グレームは「どれがいい？」と聞いて、リノは「これ！」と言いました。",
			romaji: "Gureemu wa \"Dore ga ii?\" to kiite, Rino wa \"Kore!\" to iimashita.",
			english: "Graeme asked “Which one’s good?” and Rino said “This!”",
		},
	},
	{
		english: "Here",
		romaji: "koko",
		hiragana: "ここ",
		partOfSpeech: "adverb",
		jlpt: "N5",
		example: {
			japanese: "リノは「ここに座って」と言って、グレームは座りました。",
			romaji: "Rino wa \"Koko ni suwatte\" to itte, Gureemu wa suwarimashita.",
			english: "Rino said “Sit here,” and Graeme sat down.",
		},
	},
	{
		english: "There",
		romaji: "soko",
		hiragana: "そこ",
		partOfSpeech: "adverb",
		jlpt: "N5",
		example: {
			japanese: "グレームは「そこだよね？」と聞いて、リノは「うん」と言いました。",
			romaji: "Gureemu wa \"Soko da yo ne?\" to kiite, Rino wa \"Un\" to iimashita.",
			english: "Graeme asked “It’s there, right?” and Rino said “Yeah.”",
		},
	},
	{
		english: "Over there",
		romaji: "asoko",
		hiragana: "あそこ",
		partOfSpeech: "adverb",
		jlpt: "N5",
		example: {
			japanese: "リノは「あそこに駅がある」と言って、グレームは走りました。",
			romaji: "Rino wa \"Asoko ni eki ga aru\" to itte, Gureemu wa hashirimashita.",
			english: "Rino said “The station is over there,” and Graeme ran.",
		},
	},
	{
		english: "Left",
		romaji: "hidari",
		hiragana: "ひだり",
		kanji: "左",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "グレームが迷って、リノは「左！」と言いました。",
			romaji: "Gureemu ga mayotte, Rino wa \"Hidari!\" to iimashita.",
			english: "Graeme got lost, and Rino said, “Left!”",
		},
	},
	{
		english: "Right",
		romaji: "migi",
		hiragana: "みぎ",
		kanji: "右",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "リノは「右に曲がって」と言って、グレームは右に曲がりました。",
			romaji: "Rino wa \"Migi ni magatte\" to itte, Gureemu wa migi ni magarimashita.",
			english: "Rino said “Turn right,” and Graeme turned right.",
		},
	},
	{
		english: "Straight",
		romaji: "massugu",
		hiragana: "まっすぐ",
		partOfSpeech: "adverb",
		jlpt: "N5",
		example: {
			japanese: "グレームは「まっすぐ行くね」と言って、リノはうなずきました。",
			romaji: "Gureemu wa \"Massugu iku ne\" to itte, Rino wa unazukimashita.",
			english: "Graeme said “I’ll go straight,” and Rino nodded.",
		},
	},
	{
		english: "Near",
		romaji: "chikai",
		hiragana: "ちかい",
		kanji: "近い",
		partOfSpeech: "i-adjective",
		jlpt: "N5",
		example: {
			japanese: "駅は近いので、グレームとリノは歩きました。",
			romaji: "Eki wa chikai no de, Gureemu to Rino wa arukimashita.",
			english: "The station was near, so Graeme and Rino walked.",
		},
	},
	{
		english: "Far",
		romaji: "tooi",
		hiragana: "とおい",
		kanji: "遠い",
		partOfSpeech: "i-adjective",
		jlpt: "N5",
		example: {
			japanese: "北海道は遠いけど、グレームとリノは行きたいです。",
			romaji: "Hokkaidou wa tooi kedo, Gureemu to Rino wa ikitai desu.",
			english: "Hokkaido is far, but Graeme and Rino want to go.",
		},
	},
	{
		english: "Entrance",
		romaji: "iriguchi",
		hiragana: "いりぐち",
		kanji: "入口",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "リノは「入口はあそこ」と言って、グレームは走りました。",
			romaji: "Rino wa \"Iriguchi wa asoko\" to itte, Gureemu wa hashirimashita.",
			english: "Rino said “The entrance is over there,” and Graeme ran.",
		},
	},
	{
		english: "Exit",
		romaji: "deguchi",
		hiragana: "でぐち",
		kanji: "出口",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "グレームは「出口どこ？」と聞いて、リノは「右だよ」と言いました。",
			romaji: "Gureemu wa \"Deguchi doko?\" to kiite, Rino wa \"Migi da yo\" to iimashita.",
			english: "Graeme asked “Where’s the exit?” and Rino said “To the right.”",
		},
	},
	{
		english: "Station",
		romaji: "eki",
		hiragana: "えき",
		kanji: "駅",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "横浜駅でグレームとリノは待ち合わせしました。",
			romaji: "Yokohama-eki de Gureemu to Rino wa machiawase shimashita.",
			english: "Graeme and Rino met up at Yokohama Station.",
		},
	},
	{
		english: "Train",
		romaji: "densha",
		hiragana: "でんしゃ",
		kanji: "電車",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "グレームとリノは電車に乗って、北海道の話をしました。",
			romaji: "Gureemu to Rino wa densha ni notte, Hokkaidou no hanashi o shimashita.",
			english: "Graeme and Rino rode the train and talked about Hokkaido.",
		},
	},
	{
		english: "Bus",
		romaji: "basu",
		hiragana: "バス",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "雨の日、グレームとリノはバスで帰りました。",
			romaji: "Ame no hi, Gureemu to Rino wa basu de kaerimashita.",
			english: "On a rainy day, Graeme and Rino went home by bus.",
		},
	},
	{
		english: "Taxi",
		romaji: "takushii",
		hiragana: "タクシー",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "グレームは「タクシー！」と言って、リノは笑いました。",
			romaji: "Gureemu wa \"Takushii!\" to itte, Rino wa waraimashita.",
			english: "Graeme shouted “Taxi!” and Rino laughed.",
		},
	},
	{
		english: "Bicycle",
		romaji: "jitensha",
		hiragana: "じてんしゃ",
		kanji: "自転車",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "スコットランドみたいに風が強くて、グレームとリノは自転車をやめました。",
			romaji:
				"Sukottorando mitai ni kaze ga tsuyokute, Gureemu to Rino wa jitensha o yamemashita.",
			english: "The wind was strong like in Scotland, so Graeme and Rino stopped cycling.",
		},
	},
	{
		english: "Car",
		romaji: "kuruma",
		hiragana: "くるま",
		kanji: "車",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "リノの車は小さいけど、グレームは気に入りました。",
			romaji: "Rino no kuruma wa chiisai kedo, Gureemu wa kiniirimashita.",
			english: "Rino’s car is small, but Graeme liked it.",
		},
	},
	{
		english: "Ticket",
		romaji: "kippu",
		hiragana: "きっぷ",
		kanji: "切符",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "グレームは切符を買って、リノは改札へ走りました。",
			romaji: "Gureemu wa kippu o katte, Rino wa kaisatsu e hashirimashita.",
			english: "Graeme bought tickets, and Rino ran to the gates.",
		},
	},
	{
		english: "Map",
		romaji: "chizu",
		hiragana: "ちず",
		kanji: "地図",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "地図を見て、リノは「こっち」と言い、グレームはついていきました。",
			romaji: "Chizu o mite, Rino wa \"Kocchi\" to ii, Gureemu wa tsuite ikimashita.",
			english: "Looking at the map, Rino said “This way,” and Graeme followed.",
		},
	},
	{
		english: "Toilet / bathroom",
		romaji: "toire",
		hiragana: "トイレ",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "グレームが「トイレ…」と言って、リノは急ぎました。",
			romaji: "Gureemu ga \"Toire...\" to itte, Rino wa isogimashita.",
			english: "Graeme said “Bathroom…” and Rino hurried.",
		},
	},
	{
		english: "Hotel",
		romaji: "hoteru",
		hiragana: "ホテル",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "北海道のホテルで、グレームとリノは温泉をさがしました。",
			romaji: "Hokkaidou no hoteru de, Gureemu to Rino wa onsen o sagashimashita.",
			english: "At a Hokkaido hotel, Graeme and Rino looked for a hot spring.",
		},
	},
	{
		english: "Airport",
		romaji: "kuukou",
		hiragana: "くうこう",
		kanji: "空港",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "空港で、リノは「パスポートある？」と聞いて、グレームは青ざめました。",
			romaji:
				"Kuukou de, Rino wa \"Pasupooto aru?\" to kiite, Gureemu wa aozamemashita.",
			english: "At the airport, Rino asked “Do you have your passport?” and Graeme went pale.",
		},
	},
	{
		english: "Restaurant",
		romaji: "resutoran",
		hiragana: "レストラン",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "レストランで、グレームとリノはメニューを見ました。",
			romaji: "Resutoran de, Gureemu to Rino wa menyuu o mimashita.",
			english: "At a restaurant, Graeme and Rino looked at the menu.",
		},
	},
	{
		english: "Menu",
		romaji: "menyuu",
		hiragana: "メニュー",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "リノはメニューを指さして、グレームは「それ！」と言いました。",
			romaji: "Rino wa menyuu o yubisashite, Gureemu wa \"Sore!\" to iimashita.",
			english: "Rino pointed at the menu, and Graeme said “That one!”",
		},
	},
	{
		english: "Order",
		romaji: "chuumon",
		hiragana: "ちゅうもん",
		kanji: "注文",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "注文が多すぎて、リノはグレームに「落ち着いて」と言いました。",
			romaji: "Chuumon ga oosugite, Rino wa Gureemu ni \"Ochitsuite\" to iimashita.",
			english: "The order was too big, and Rino told Graeme “Calm down.”",
		},
	},
	{
		english: "Checkout / bill",
		romaji: "okaikei",
		hiragana: "おかいけい",
		kanji: "お会計",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "グレームは「お会計お願いします」と言って、リノはにやっとしました。",
			romaji:
				"Gureemu wa \"Okaikei onegaishimasu\" to itte, Rino wa niyatto shimashita.",
			english: "Graeme said “Check, please,” and Rino grinned.",
		},
	},
	{
		english: "Reservation",
		romaji: "yoyaku",
		hiragana: "よやく",
		kanji: "予約",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "リノは予約をしていて、グレームは安心しました。",
			romaji: "Rino wa yoyaku o shite ite, Gureemu wa anshin shimashita.",
			english: "Rino had made a reservation, and Graeme felt relieved.",
		},
	},
	{
		english: "To go",
		romaji: "iku",
		hiragana: "いく",
		kanji: "行く",
		partOfSpeech: "verb",
		jlpt: "N5",
		example: {
			japanese: "グレームは北海道に行くと言って、リノは「いいね！」と言いました。",
			romaji: "Gureemu wa Hokkaidou ni iku to itte, Rino wa \"Ii ne!\" to iimashita.",
			english: "Graeme said he’s going to Hokkaido, and Rino said “Nice!”",
		},
	},
	{
		english: "To come",
		romaji: "kuru",
		hiragana: "くる",
		kanji: "来る",
		partOfSpeech: "verb",
		jlpt: "N5",
		example: {
			japanese: "リノが「すぐ来るよ」と言って、グレームは待ちました。",
			romaji: "Rino ga \"Sugu kuru yo\" to itte, Gureemu wa machimashita.",
			english: "Rino said “I’ll come right away,” and Graeme waited.",
		},
	},
	{
		english: "To return (home)",
		romaji: "kaeru",
		hiragana: "かえる",
		kanji: "帰る",
		partOfSpeech: "verb",
		jlpt: "N5",
		example: {
			japanese: "遅くなって、グレームとリノは家に帰りました。",
			romaji: "Osoku natte, Gureemu to Rino wa ie ni kaerimashita.",
			english: "It got late, so Graeme and Rino went home.",
		},
	},
	{
		english: "To leave / exit",
		romaji: "deru",
		hiragana: "でる",
		kanji: "出る",
		partOfSpeech: "verb",
		jlpt: "N5",
		example: {
			japanese: "グレームがドアから出ると、リノが「待って！」と言いました。",
			romaji: "Gureemu ga doa kara deru to, Rino ga \"Matte!\" to iimashita.",
			english: "As Graeme left through the door, Rino said “Wait!”",
		},
	},
	{
		english: "To enter",
		romaji: "hairu",
		hiragana: "はいる",
		kanji: "入る",
		partOfSpeech: "verb",
		jlpt: "N5",
		example: {
			japanese: "リノが先に店に入って、グレームはついていきました。",
			romaji: "Rino ga saki ni mise ni haitte, Gureemu wa tsuite ikimashita.",
			english: "Rino entered the shop first, and Graeme followed.",
		},
	},
	{
		english: "To meet",
		romaji: "au",
		hiragana: "あう",
		kanji: "会う",
		partOfSpeech: "verb",
		jlpt: "N5",
		example: {
			japanese: "明日、横浜でグレームとリノは会います。",
			romaji: "Ashita, Yokohama de Gureemu to Rino wa aimasu.",
			english: "Tomorrow, Graeme and Rino will meet in Yokohama.",
		},
	},
	{
		english: "To see / watch",
		romaji: "miru",
		hiragana: "みる",
		kanji: "見る",
		partOfSpeech: "verb",
		jlpt: "N5",
		example: {
			japanese: "グレームとリノは映画を見るのが好きです。",
			romaji: "Gureemu to Rino wa eiga o miru no ga suki desu.",
			english: "Graeme and Rino like watching movies.",
		},
	},
	{
		english: "To listen / ask",
		romaji: "kiku",
		hiragana: "きく",
		kanji: "聞く",
		partOfSpeech: "verb",
		jlpt: "N5",
		example: {
			japanese: "リノは音楽を聞いて、グレームは歌詞を聞きました。",
			romaji: "Rino wa ongaku o kiite, Gureemu wa kashi o kikimashita.",
			english: "Rino listened to music, and Graeme listened to the lyrics.",
		},
	},
	{
		english: "To speak",
		romaji: "hanasu",
		hiragana: "はなす",
		kanji: "話す",
		partOfSpeech: "verb",
		jlpt: "N5",
		example: {
			japanese: "グレームは日本語を話して、リノは英語を話しました。",
			romaji: "Gureemu wa nihongo o hanashite, Rino wa eigo o hanashimashita.",
			english: "Graeme spoke Japanese, and Rino spoke English.",
		},
	},
	{
		english: "To say",
		romaji: "iu",
		hiragana: "いう",
		kanji: "言う",
		partOfSpeech: "verb",
		jlpt: "N5",
		example: {
			japanese: "リノが何か言って、グレームはびっくりしました。",
			romaji: "Rino ga nanika itte, Gureemu wa bikkuri shimashita.",
			english: "Rino said something, and Graeme was surprised.",
		},
	},
	{
		english: "To read",
		romaji: "yomu",
		hiragana: "よむ",
		kanji: "読む",
		partOfSpeech: "verb",
		jlpt: "N5",
		example: {
			japanese: "リノは本を読んで、グレームは新聞を読みました。",
			romaji: "Rino wa hon o yonde, Gureemu wa shinbun o yomimashita.",
			english: "Rino read a book, and Graeme read the newspaper.",
		},
	},
	{
		english: "To write",
		romaji: "kaku",
		hiragana: "かく",
		kanji: "書く",
		partOfSpeech: "verb",
		jlpt: "N5",
		example: {
			japanese: "グレームはメモを書くと言って、リノはペンを渡しました。",
			romaji: "Gureemu wa memo o kaku to itte, Rino wa pen o watashimashita.",
			english: "Graeme said he’d write a note, and Rino handed him a pen.",
		},
	},
	{
		english: "To buy",
		romaji: "kau",
		hiragana: "かう",
		kanji: "買う",
		partOfSpeech: "verb",
		jlpt: "N5",
		example: {
			japanese: "おみやげを買って、グレームはリノに見せました。",
			romaji: "Omiyage o katte, Gureemu wa Rino ni misemashita.",
			english: "Graeme bought a souvenir and showed it to Rino.",
		},
	},
	{
		english: "To sell",
		romaji: "uru",
		hiragana: "うる",
		kanji: "売る",
		partOfSpeech: "verb",
		jlpt: "N5",
		example: {
			japanese: "リノは「それは売らない」と言って、グレームはあきらめました。",
			romaji: "Rino wa \"Sore wa uranai\" to itte, Gureemu wa akiramemashita.",
			english: "Rino said “I’m not selling that,” and Graeme gave up.",
		},
	},
	{
		english: "To make",
		romaji: "tsukuru",
		hiragana: "つくる",
		kanji: "作る",
		partOfSpeech: "verb",
		jlpt: "N5",
		example: {
			japanese: "リノは朝ご飯を作って、グレームは「すごい！」と言いました。",
			romaji: "Rino wa asagohan o tsukutte, Gureemu wa \"Sugoi!\" to iimashita.",
			english: "Rino made breakfast, and Graeme said “Amazing!”",
		},
	},
	{
		english: "To do",
		romaji: "suru",
		hiragana: "する",
		partOfSpeech: "verb",
		jlpt: "N5",
		example: {
			japanese: "グレームは「なにする？」と聞いて、リノは「散歩する」と言いました。",
			romaji: "Gureemu wa \"Nani suru?\" to kiite, Rino wa \"Sanpo suru\" to iimashita.",
			english: "Graeme asked “What should we do?” and Rino said “Let’s take a walk.”",
		},
	},
	{
		english: "To work",
		romaji: "hataraku",
		hiragana: "はたらく",
		kanji: "働く",
		partOfSpeech: "verb",
		jlpt: "N5",
		example: {
			japanese: "グレームはよく働いて、リノは「休んで」と言いました。",
			romaji: "Gureemu wa yoku hataraite, Rino wa \"Yasunde\" to iimashita.",
			english: "Graeme worked a lot, and Rino said “Rest.”",
		},
	},
	{
		english: "To study",
		romaji: "benkyou suru",
		hiragana: "べんきょうする",
		kanji: "勉強する",
		partOfSpeech: "verb",
		jlpt: "N5",
		example: {
			japanese: "グレームとリノは毎日日本語を勉強します。",
			romaji: "Gureemu to Rino wa mainichi nihongo o benkyou shimasu.",
			english: "Graeme and Rino study Japanese every day.",
		},
	},
	{
		english: "To rest",
		romaji: "yasumu",
		hiragana: "やすむ",
		kanji: "休む",
		partOfSpeech: "verb",
		jlpt: "N5",
		example: {
			japanese: "疲れて、リノは休むと言い、グレームも休みました。",
			romaji: "Tsukarete, Rino wa yasumu to ii, Gureemu mo yasumimashita.",
			english: "Tired, Rino said she’d rest, and Graeme rested too.",
		},
	},
	{
		english: "To sleep",
		romaji: "neru",
		hiragana: "ねる",
		kanji: "寝る",
		partOfSpeech: "verb",
		jlpt: "N5",
		example: {
			japanese: "グレームは早く寝て、リノは遅く寝ました。",
			romaji: "Gureemu wa hayaku nete, Rino wa osoku nemashita.",
			english: "Graeme slept early, and Rino slept late.",
		},
	},
	{
		english: "To wake up",
		romaji: "okiru",
		hiragana: "おきる",
		kanji: "起きる",
		partOfSpeech: "verb",
		jlpt: "N5",
		example: {
			japanese: "リノが起きて、グレームを起こしました。",
			romaji: "Rino ga okite, Gureemu o okoshimashita.",
			english: "Rino woke up and woke Graeme up.",
		},
	},
	{
		english: "To walk",
		romaji: "aruku",
		hiragana: "あるく",
		kanji: "歩く",
		partOfSpeech: "verb",
		jlpt: "N5",
		example: {
			japanese: "スコットランドの話をしながら、グレームとリノは歩きました。",
			romaji: "Sukottorando no hanashi o shinagara, Gureemu to Rino wa arukimashita.",
			english: "Talking about Scotland, Graeme and Rino walked.",
		},
	},
	{
		english: "To run",
		romaji: "hashiru",
		hiragana: "はしる",
		kanji: "走る",
		partOfSpeech: "verb",
		jlpt: "N5",
		example: {
			japanese: "電車に遅れそうで、グレームとリノは走りました。",
			romaji: "Densha ni okuresou de, Gureemu to Rino wa hashirimashita.",
			english: "They were about to miss the train, so Graeme and Rino ran.",
		},
	},
	{
		english: "To swim",
		romaji: "oyogu",
		hiragana: "およぐ",
		kanji: "泳ぐ",
		partOfSpeech: "verb",
		jlpt: "N5",
		example: {
			japanese: "夏に、グレームとリノは海で泳ぎました。",
			romaji: "Natsu ni, Gureemu to Rino wa umi de oyogimashita.",
			english: "In summer, Graeme and Rino swam in the sea.",
		},
	},
	{
		english: "To use",
		romaji: "tsukau",
		hiragana: "つかう",
		kanji: "使う",
		partOfSpeech: "verb",
		jlpt: "N5",
		example: {
			japanese: "リノはアプリを使って、グレームは地図を使いました。",
			romaji: "Rino wa apuri o tsukatte, Gureemu wa chizu o tsukaimashita.",
			english: "Rino used an app, and Graeme used a map.",
		},
	},
	{
		english: "To wait",
		romaji: "matsu",
		hiragana: "まつ",
		kanji: "待つ",
		partOfSpeech: "verb",
		jlpt: "N5",
		example: {
			japanese: "グレームは待って、リノは「あと5分！」と言いました。",
			romaji: "Gureemu wa matte, Rino wa \"Ato go-fun!\" to iimashita.",
			english: "Graeme waited, and Rino said “Five more minutes!”",
		},
	},
	{
		english: "To hurry",
		romaji: "isogu",
		hiragana: "いそぐ",
		kanji: "急ぐ",
		partOfSpeech: "verb",
		jlpt: "N5",
		example: {
			japanese: "リノが「急いで！」と言って、グレームは急ぎました。",
			romaji: "Rino ga \"Isoide!\" to itte, Gureemu wa isogimashita.",
			english: "Rino said “Hurry!” and Graeme hurried.",
		},
	},
	{
		english: "To start",
		romaji: "hajimeru",
		hiragana: "はじめる",
		kanji: "始める",
		partOfSpeech: "verb",
		jlpt: "N5",
		example: {
			japanese: "グレームが話を始めて、リノは聞きました。",
			romaji: "Gureemu ga hanashi o hajimete, Rino wa kikimashita.",
			english: "Graeme started talking, and Rino listened.",
		},
	},
	{
		english: "To finish",
		romaji: "owaru",
		hiragana: "おわる",
		kanji: "終わる",
		partOfSpeech: "verb",
		jlpt: "N5",
		example: {
			japanese: "勉強が終わって、グレームとリノはコーヒーを飲みました。",
			romaji: "Benkyou ga owatte, Gureemu to Rino wa koohii o nomimashita.",
			english: "After studying finished, Graeme and Rino drank coffee.",
		},
	},
	{
		english: "To think",
		romaji: "omou",
		hiragana: "おもう",
		kanji: "思う",
		partOfSpeech: "verb",
		jlpt: "N5",
		example: {
			japanese: "グレームは「それはいい」と思って、リノもそう思いました。",
			romaji: "Gureemu wa \"Sore wa ii\" to omotte, Rino mo sou omoimashita.",
			english: "Graeme thought “That’s good,” and Rino thought so too.",
		},
	},
	{
		english: "To know",
		romaji: "shiru",
		hiragana: "しる",
		kanji: "知る",
		partOfSpeech: "verb",
		jlpt: "N5",
		example: {
			japanese: "リノは答えを知っていて、グレームは助かりました。",
			romaji: "Rino wa kotae o shitte ite, Gureemu wa tasukarimashita.",
			english: "Rino knew the answer, and Graeme was saved.",
		},
	},
	{
		english: "To remember",
		romaji: "oboeru",
		hiragana: "おぼえる",
		kanji: "覚える",
		partOfSpeech: "verb",
		jlpt: "N5",
		example: {
			japanese: "グレームは単語を覚えて、リノは「天才？」と言いました。",
			romaji: "Gureemu wa tango o oboete, Rino wa \"Tensai?\" to iimashita.",
			english: "Graeme memorized the words, and Rino said “Genius?”",
		},
	},
	{
		english: "To forget",
		romaji: "wasureru",
		hiragana: "わすれる",
		kanji: "忘れる",
		partOfSpeech: "verb",
		jlpt: "N5",
		example: {
			japanese: "グレームが切符を忘れて、リノは「うそでしょ」と言いました。",
			romaji: "Gureemu ga kippu o wasurete, Rino wa \"Uso desho\" to iimashita.",
			english: "Graeme forgot the ticket, and Rino said “No way.”",
		},
	},
	{
		english: "To teach",
		romaji: "oshieru",
		hiragana: "おしえる",
		kanji: "教える",
		partOfSpeech: "verb",
		jlpt: "N5",
		example: {
			japanese: "リノは日本語を教えて、グレームはメモを書きました。",
			romaji: "Rino wa nihongo o oshiete, Gureemu wa memo o kakimashita.",
			english: "Rino taught Japanese, and Graeme wrote notes.",
		},
	},
	{
		english: "To learn",
		romaji: "narau",
		hiragana: "ならう",
		kanji: "習う",
		partOfSpeech: "verb",
		jlpt: "N5",
		example: {
			japanese: "グレームはリノから料理を習って、リノは誇らしげでした。",
			romaji: "Gureemu wa Rino kara ryouri o naratte, Rino wa hokorashige deshita.",
			english: "Graeme learned cooking from Rino, and Rino looked proud.",
		},
	},
	{
		english: "To help (assist)",
		romaji: "tetsudau",
		hiragana: "てつだう",
		kanji: "手伝う",
		partOfSpeech: "verb",
		jlpt: "N5",
		example: {
			japanese: "グレームが手伝うと言って、リノは「ありがとう」と言いました。",
			romaji: "Gureemu ga tetsudau to itte, Rino wa \"Arigatou\" to iimashita.",
			english: "Graeme said he’d help, and Rino said “Thanks.”",
		},
	},
	{
		english: "To help / save",
		romaji: "tasukeru",
		hiragana: "たすける",
		kanji: "助ける",
		partOfSpeech: "verb",
		jlpt: "N5",
		example: {
			japanese: "リノが助けてくれて、グレームは安心しました。",
			romaji: "Rino ga tasukete kurete, Gureemu wa anshin shimashita.",
			english: "Rino helped, and Graeme felt relieved.",
		},
	},
	{
		english: "To lend",
		romaji: "kasu",
		hiragana: "かす",
		kanji: "貸す",
		partOfSpeech: "verb",
		jlpt: "N5",
		example: {
			japanese: "グレームは傘を貸して、リノは「神！」と言いました。",
			romaji: "Gureemu wa kasa o kashite, Rino wa \"Kami!\" to iimashita.",
			english: "Graeme lent an umbrella, and Rino said “You’re a legend!”",
		},
	},
	{
		english: "To borrow",
		romaji: "kariru",
		hiragana: "かりる",
		kanji: "借りる",
		partOfSpeech: "verb",
		jlpt: "N5",
		example: {
			japanese: "リノはグレームから本を借りて、すぐ読みました。",
			romaji: "Rino wa Gureemu kara hon o karite, sugu yomimashita.",
			english: "Rino borrowed a book from Graeme and read it right away.",
		},
	},
	{
		english: "To open",
		romaji: "akeru",
		hiragana: "あける",
		kanji: "開ける",
		partOfSpeech: "verb",
		jlpt: "N5",
		example: {
			japanese: "グレームがドアを開けて、リノは「寒い！」と言いました。",
			romaji: "Gureemu ga doa o akete, Rino wa \"Samui!\" to iimashita.",
			english: "Graeme opened the door, and Rino said “It’s cold!”",
		},
	},
	{
		english: "To close",
		romaji: "shimeru",
		hiragana: "しめる",
		kanji: "閉める",
		partOfSpeech: "verb",
		jlpt: "N5",
		example: {
			japanese: "リノは「ドア閉めて」と言って、グレームは閉めました。",
			romaji: "Rino wa \"Doa shimete\" to itte, Gureemu wa shimemashita.",
			english: "Rino said “Close the door,” and Graeme closed it.",
		},
	},
	{
		english: "To turn on",
		romaji: "tsukeru",
		hiragana: "つける",
		kanji: "付ける",
		partOfSpeech: "verb",
		jlpt: "N5",
		example: {
			japanese: "暗くて、グレームは電気をつけて、リノはほっとしました。",
			romaji: "Kura kute, Gureemu wa denki o tsukete, Rino wa hotto shimashita.",
			english: "It was dark, so Graeme turned on the light and Rino relaxed.",
		},
	},
	{
		english: "To turn off",
		romaji: "kesu",
		hiragana: "けす",
		kanji: "消す",
		partOfSpeech: "verb",
		jlpt: "N5",
		example: {
			japanese: "寝る前に、リノは電気を消して、グレームは「えらい」と言いました。",
			romaji: "Neru mae ni, Rino wa denki o keshite, Gureemu wa \"Erai\" to iimashita.",
			english: "Before sleeping, Rino turned off the light and Graeme said “Good job.”",
		},
	},
	{
		english: "To call (phone)",
		romaji: "denwa suru",
		hiragana: "でんわする",
		kanji: "電話する",
		partOfSpeech: "verb",
		jlpt: "N5",
		example: {
			japanese: "グレームが電話すると言って、リノはメモを用意しました。",
			romaji: "Gureemu ga denwa suru to itte, Rino wa memo o youi shimashita.",
			english: "Graeme said he’d call, and Rino got a note ready.",
		},
	},
	{
		english: "To take (a photo)",
		romaji: "toru",
		hiragana: "とる",
		kanji: "撮る",
		partOfSpeech: "verb",
		jlpt: "N5",
		example: {
			japanese: "横浜で、リノは写真を撮って、グレームはポーズしました。",
			romaji: "Yokohama de, Rino wa shashin o totte, Gureemu wa poozu shimashita.",
			english: "In Yokohama, Rino took a photo and Graeme posed.",
		},
	},
	{
		english: "Time",
		romaji: "jikan",
		hiragana: "じかん",
		kanji: "時間",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "リノは「時間ある？」と聞いて、グレームは「少しある」と言いました。",
			romaji: "Rino wa \"Jikan aru?\" to kiite, Gureemu wa \"Sukoshi aru\" to iimashita.",
			english: "Rino asked “Do you have time?” and Graeme said “A little.”",
		},
	},
	{
		english: "Now",
		romaji: "ima",
		hiragana: "いま",
		kanji: "今",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "グレームは「今行く！」と言って、リノは「やっと！」と言いました。",
			romaji: "Gureemu wa \"Ima iku!\" to itte, Rino wa \"Yatto!\" to iimashita.",
			english: "Graeme said “I’m going now!” and Rino said “Finally!”",
		},
	},
	{
		english: "Tomorrow",
		romaji: "ashita",
		hiragana: "あした",
		kanji: "明日",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "明日、グレームとリノはスコットランドの話を続けます。",
			romaji: "Ashita, Gureemu to Rino wa Sukottorando no hanashi o tsudzukemasu.",
			english: "Tomorrow, Graeme and Rino will continue the Scotland talk.",
		},
	},
	{
		english: "Yesterday",
		romaji: "kinou",
		hiragana: "きのう",
		kanji: "昨日",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "昨日、リノは北海道の写真を見せて、グレームは驚きました。",
			romaji: "Kinou, Rino wa Hokkaidou no shashin o misete, Gureemu wa odorokimashita.",
			english: "Yesterday, Rino showed Hokkaido photos and Graeme was amazed.",
		},
	},
	{
		english: "Morning",
		romaji: "asa",
		hiragana: "あさ",
		kanji: "朝",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "朝、グレームはコーヒーを飲んで、リノはお茶を飲みます。",
			romaji: "Asa, Gureemu wa koohii o nonde, Rino wa ocha o nomimasu.",
			english: "In the morning, Graeme drinks coffee and Rino drinks tea.",
		},
	},
	{
		english: "Afternoon",
		romaji: "gogo",
		hiragana: "ごご",
		kanji: "午後",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "午後、グレームとリノは散歩しました。",
			romaji: "Gogo, Gureemu to Rino wa sanpo shimashita.",
			english: "In the afternoon, Graeme and Rino took a walk.",
		},
	},
	{
		english: "Evening",
		romaji: "yuugata",
		hiragana: "ゆうがた",
		kanji: "夕方",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "夕方、リノは料理して、グレームは手伝いました。",
			romaji: "Yuugata, Rino wa ryouri shite, Gureemu wa tetsudaimashita.",
			english: "In the evening, Rino cooked and Graeme helped.",
		},
	},
	{
		english: "Night",
		romaji: "yoru",
		hiragana: "よる",
		kanji: "夜",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "夜、グレームとリノは映画を見ました。",
			romaji: "Yoru, Gureemu to Rino wa eiga o mimashita.",
			english: "At night, Graeme and Rino watched a movie.",
		},
	},
	{
		english: "Week",
		romaji: "shuu",
		hiragana: "しゅう",
		kanji: "週",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "今週、グレームとリノは横浜に行きます。",
			romaji: "Konshuu, Gureemu to Rino wa Yokohama ni ikimasu.",
			english: "This week, Graeme and Rino are going to Yokohama.",
		},
	},
	{
		english: "Month",
		romaji: "tsuki",
		hiragana: "つき",
		kanji: "月",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "来月、グレームとリノは北海道に行きたいです。",
			romaji: "Raigetsu, Gureemu to Rino wa Hokkaidou ni ikitai desu.",
			english: "Next month, Graeme and Rino want to go to Hokkaido.",
		},
	},
	{
		english: "Year",
		romaji: "toshi",
		hiragana: "とし",
		kanji: "年",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "今年、グレームとリノは日本語が上手になりました。",
			romaji: "Kotoshi, Gureemu to Rino wa nihongo ga jouzu ni narimashita.",
			english: "This year, Graeme and Rino got better at Japanese.",
		},
	},
	{
		english: "Minute",
		romaji: "fun",
		hiragana: "ふん",
		kanji: "分",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "リノは「あと5分」と言って、グレームは深呼吸しました。",
			romaji: "Rino wa \"Ato go-fun\" to itte, Gureemu wa shinkokyuu shimashita.",
			english: "Rino said “Five more minutes,” and Graeme took a deep breath.",
		},
	},
	{
		english: "Hour",
		romaji: "ji",
		hiragana: "じ",
		kanji: "時",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "グレームは「今、3時だよ」と言って、リノは驚きました。",
			romaji: "Gureemu wa \"Ima, san-ji da yo\" to itte, Rino wa odorokimashita.",
			english: "Graeme said “It’s 3 o’clock now,” and Rino was surprised.",
		},
	},
	{
		english: "Day",
		romaji: "hi",
		hiragana: "ひ",
		kanji: "日",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "いい日で、グレームとリノは笑いました。",
			romaji: "Ii hi de, Gureemu to Rino wa waraimashita.",
			english: "It was a good day, and Graeme and Rino laughed.",
		},
	},
	{
		english: "Birthday",
		romaji: "tanjoubi",
		hiragana: "たんじょうび",
		kanji: "誕生日",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "リノの誕生日に、グレームはケーキを買いました。",
			romaji: "Rino no tanjoubi ni, Gureemu wa keeki o kaimashita.",
			english: "On Rino’s birthday, Graeme bought a cake.",
		},
	},
	{
		english: "Holiday / break",
		romaji: "yasumi",
		hiragana: "やすみ",
		kanji: "休み",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "休みに、グレームとリノは北海道の計画を立てました。",
			romaji: "Yasumi ni, Gureemu to Rino wa Hokkaidou no keikaku o tatemashita.",
			english: "On their break, Graeme and Rino made a Hokkaido plan.",
		},
	},
	{
		english: "Work / job",
		romaji: "shigoto",
		hiragana: "しごと",
		kanji: "仕事",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "仕事のあと、グレームとリノはラーメンを食べました。",
			romaji: "Shigoto no ato, Gureemu to Rino wa raamen o tabemashita.",
			english: "After work, Graeme and Rino ate ramen.",
		},
	},
	{
		english: "School",
		romaji: "gakkou",
		hiragana: "がっこう",
		kanji: "学校",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "学校で、リノは勉強して、グレームは質問しました。",
			romaji: "Gakkou de, Rino wa benkyou shite, Gureemu wa shitsumon shimashita.",
			english: "At school, Rino studied and Graeme asked questions.",
		},
	},
	{
		english: "Company",
		romaji: "kaisha",
		hiragana: "かいしゃ",
		kanji: "会社",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "会社で、グレームは忙しくて、リノはコーヒーをくれました。",
			romaji: "Kaisha de, Gureemu wa isogashikute, Rino wa koohii o kuremashita.",
			english: "At the company, Graeme was busy, and Rino gave him coffee.",
		},
	},
	{
		english: "Home / house",
		romaji: "ie",
		hiragana: "いえ",
		kanji: "家",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "家に帰って、グレームとリノはほっとしました。",
			romaji: "Ie ni kaette, Gureemu to Rino wa hotto shimashita.",
			english: "They got home, and Graeme and Rino felt relieved.",
		},
	},
	{
		english: "Room",
		romaji: "heya",
		hiragana: "へや",
		kanji: "部屋",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "部屋がきれいで、グレームは感動して、リノは自慢しました。",
			romaji: "Heya ga kirei de, Gureemu wa kandou shite, Rino wa jiman shimashita.",
			english: "The room was clean; Graeme was impressed and Rino bragged.",
		},
	},
	{
		english: "Kitchen",
		romaji: "daidokoro",
		hiragana: "だいどころ",
		kanji: "台所",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "台所で、リノは料理して、グレームは味見しました。",
			romaji: "Daidokoro de, Rino wa ryouri shite, Gureemu wa ajimi shimashita.",
			english: "In the kitchen, Rino cooked and Graeme taste-tested.",
		},
	},
	{
		english: "Bath",
		romaji: "ofuro",
		hiragana: "おふろ",
		kanji: "お風呂",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "北海道で、グレームとリノはお風呂に入って温まりました。",
			romaji: "Hokkaidou de, Gureemu to Rino wa ofuro ni haitte atatamarimashita.",
			english: "In Hokkaido, Graeme and Rino took a bath and warmed up.",
		},
	},
	{
		english: "Bed",
		romaji: "beddo",
		hiragana: "ベッド",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "ベッドがふかふかで、グレームとリノはすぐ寝ました。",
			romaji: "Beddo ga fukafuka de, Gureemu to Rino wa sugu nemashita.",
			english: "The bed was fluffy, so Graeme and Rino fell asleep quickly.",
		},
	},
	{
		english: "Desk",
		romaji: "tsukue",
		hiragana: "つくえ",
		kanji: "机",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "机で、リノは書いて、グレームは読んでいました。",
			romaji: "Tsukue de, Rino wa kaite, Gureemu wa yonde imashita.",
			english: "At the desk, Rino was writing and Graeme was reading.",
		},
	},
	{
		english: "Table",
		romaji: "teeburu",
		hiragana: "テーブル",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "テーブルにコーヒーがあって、グレームとリノはにっこりしました。",
			romaji: "Teeburu ni koohii ga atte, Gureemu to Rino wa nikkori shimashita.",
			english: "There was coffee on the table, and Graeme and Rino smiled.",
		},
	},
	{
		english: "Chair",
		romaji: "isu",
		hiragana: "いす",
		kanji: "椅子",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "リノは椅子を引いて、グレームは「ありがとう」と言いました。",
			romaji: "Rino wa isu o hiite, Gureemu wa \"Arigatou\" to iimashita.",
			english: "Rino pulled out a chair, and Graeme said “Thanks.”",
		},
	},
	{
		english: "Bag",
		romaji: "kaban",
		hiragana: "かばん",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "グレームはかばんを忘れて、リノは「また？」と言いました。",
			romaji: "Gureemu wa kaban o wasurete, Rino wa \"Mata?\" to iimashita.",
			english: "Graeme forgot his bag, and Rino said “Again?”",
		},
	},
	{
		english: "Wallet",
		romaji: "saifu",
		hiragana: "さいふ",
		kanji: "財布",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "リノは財布を確認して、グレームは安心しました。",
			romaji: "Rino wa saifu o kakunin shite, Gureemu wa anshin shimashita.",
			english: "Rino checked the wallet, and Graeme felt relieved.",
		},
	},
	{
		english: "Smartphone",
		romaji: "sumaho",
		hiragana: "スマホ",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "グレームのスマホが鳴って、リノは「人気者だね」と言いました。",
			romaji: "Gureemu no sumaho ga natte, Rino wa \"Ninkimono da ne\" to iimashita.",
			english: "Graeme’s phone rang, and Rino said “You’re popular.”",
		},
	},
	{
		english: "Key",
		romaji: "kagi",
		hiragana: "かぎ",
		kanji: "鍵",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "グレームが鍵を見つけて、リノは拍手しました。",
			romaji: "Gureemu ga kagi o mitsukete, Rino wa hakushu shimashita.",
			english: "Graeme found the key, and Rino applauded.",
		},
	},
	{
		english: "Umbrella",
		romaji: "kasa",
		hiragana: "かさ",
		kanji: "傘",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "雨で、リノは傘をさして、グレームは「ありがとう」と言いました。",
			romaji: "Ame de, Rino wa kasa o sashite, Gureemu wa \"Arigatou\" to iimashita.",
			english: "In the rain, Rino held an umbrella and Graeme said “Thanks.”",
		},
	},
	{
		english: "Shoes",
		romaji: "kutsu",
		hiragana: "くつ",
		kanji: "靴",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "グレームは靴をはいて、リノは「早いね」と言いました。",
			romaji: "Gureemu wa kutsu o haite, Rino wa \"Hayai ne\" to iimashita.",
			english: "Graeme put on his shoes quickly, and Rino said “That was fast.”",
		},
	},
	{
		english: "Clothes",
		romaji: "fuku",
		hiragana: "ふく",
		kanji: "服",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "北海道は寒いので、リノは服を多めに持ってきて、グレームは感謝しました。",
			romaji:
				"Hokkaidou wa samui no de, Rino wa fuku o oome ni motte kite, Gureemu wa kansha shimashita.",
			english: "Since Hokkaido is cold, Rino brought extra clothes and Graeme was grateful.",
		},
	},
	{
		english: "Hat",
		romaji: "boushi",
		hiragana: "ぼうし",
		kanji: "帽子",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "リノは帽子をかぶって、グレームは「似合う！」と言いました。",
			romaji: "Rino wa boushi o kabutte, Gureemu wa \"Niau!\" to iimashita.",
			english: "Rino put on a hat, and Graeme said “It suits you!”",
		},
	},
	{
		english: "Glasses",
		romaji: "megane",
		hiragana: "めがね",
		kanji: "眼鏡",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "グレームは眼鏡をかけて、リノは「先生みたい」と言いました。",
			romaji: "Gureemu wa megane o kakete, Rino wa \"Sensei mitai\" to iimashita.",
			english: "Graeme put on glasses, and Rino said “You look like a teacher.”",
		},
	},
	{
		english: "Food",
		romaji: "tabemono",
		hiragana: "たべもの",
		kanji: "食べ物",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "リノは食べ物を選んで、グレームは「なんでもいい」と言いました。",
			romaji: "Rino wa tabemono o erande, Gureemu wa \"Nandemo ii\" to iimashita.",
			english: "Rino chose the food, and Graeme said “Anything is fine.”",
		},
	},
	{
		english: "Drink (noun)",
		romaji: "nomimono",
		hiragana: "のみもの",
		kanji: "飲み物",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "グレームは飲み物を買って、リノは水を選びました。",
			romaji: "Gureemu wa nomimono o katte, Rino wa mizu o erabimashita.",
			english: "Graeme bought drinks, and Rino chose water.",
		},
	},
	{
		english: "Rice / meal",
		romaji: "gohan",
		hiragana: "ごはん",
		kanji: "ご飯",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "リノは「ご飯できたよ」と言って、グレームは走りました。",
			romaji: "Rino wa \"Gohan dekita yo\" to itte, Gureemu wa hashirimashita.",
			english: "Rino said “Food’s ready,” and Graeme ran over.",
		},
	},
	{
		english: "Bread",
		romaji: "pan",
		hiragana: "パン",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "グレームはパンが好きで、リノは「フランス人？」と言いました。",
			romaji: "Gureemu wa pan ga suki de, Rino wa \"Furansujin?\" to iimashita.",
			english: "Graeme likes bread, and Rino joked “Are you French?”",
		},
	},
	{
		english: "Ramen",
		romaji: "raamen",
		hiragana: "ラーメン",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "横浜でラーメンを食べて、グレームとリノは幸せでした。",
			romaji: "Yokohama de raamen o tabete, Gureemu to Rino wa shiawase deshita.",
			english: "They ate ramen in Yokohama, and Graeme and Rino were happy.",
		},
	},
	{
		english: "Coffee",
		romaji: "koohii",
		hiragana: "コーヒー",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "グレームはコーヒーを飲んで、リノは「元気になった？」と聞きました。",
			romaji:
				"Gureemu wa koohii o nonde, Rino wa \"Genki ni natta?\" to kikimashita.",
			english: "Graeme drank coffee, and Rino asked “Feeling alive now?”",
		},
	},
	{
		english: "Tea",
		romaji: "ocha",
		hiragana: "おちゃ",
		kanji: "お茶",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "リノはお茶を入れて、グレームは「落ち着く」と言いました。",
			romaji: "Rino wa ocha o irete, Gureemu wa \"Ochitsuku\" to iimashita.",
			english: "Rino made tea, and Graeme said “That’s calming.”",
		},
	},
	{
		english: "Beer",
		romaji: "biiru",
		hiragana: "ビール",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "グレームはビールを飲みたくて、リノは「今日はだめ」と言いました。",
			romaji:
				"Gureemu wa biiru o nomitakute, Rino wa \"Kyou wa dame\" to iimashita.",
			english: "Graeme wanted beer, but Rino said “Not today.”",
		},
	},
	{
		english: "Fruit",
		romaji: "kudamono",
		hiragana: "くだもの",
		kanji: "果物",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "リノは果物を買って、グレームはりんごを選びました。",
			romaji: "Rino wa kudamono o katte, Gureemu wa ringo o erabimashita.",
			english: "Rino bought fruit, and Graeme chose apples.",
		},
	},
	{
		english: "Apple",
		romaji: "ringo",
		hiragana: "りんご",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "りんごを食べて、グレームは「甘い！」と言い、リノはにっこりしました。",
			romaji: "Ringo o tabete, Gureemu wa \"Amai!\" to ii, Rino wa nikkori shimashita.",
			english: "Eating an apple, Graeme said “Sweet!” and Rino smiled.",
		},
	},
	{
		english: "Banana",
		romaji: "banana",
		hiragana: "バナナ",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "リノはバナナを持ってきて、グレームは「助かる」と言いました。",
			romaji: "Rino wa banana o motte kite, Gureemu wa \"Tasukaru\" to iimashita.",
			english: "Rino brought a banana, and Graeme said “That helps.”",
		},
	},
	{
		english: "Fish",
		romaji: "sakana",
		hiragana: "さかな",
		kanji: "魚",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "北海道の魚はおいしいと、リノは言い、グレームはうなずきました。",
			romaji:
				"Hokkaidou no sakana wa oishii to, Rino wa ii, Gureemu wa unazukimashita.",
			english: "Rino said Hokkaido fish is delicious, and Graeme agreed.",
		},
	},
	{
		english: "Meat",
		romaji: "niku",
		hiragana: "にく",
		kanji: "肉",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "グレームは肉が好きで、リノは「野菜もね」と言いました。",
			romaji: "Gureemu wa niku ga suki de, Rino wa \"Yasai mo ne\" to iimashita.",
			english: "Graeme likes meat, and Rino said “Vegetables too, okay?”",
		},
	},
	{
		english: "Vegetables",
		romaji: "yasai",
		hiragana: "やさい",
		kanji: "野菜",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "リノは野菜を切って、グレームは「プロだ」と言いました。",
			romaji: "Rino wa yasai o kitte, Gureemu wa \"Puro da\" to iimashita.",
			english: "Rino chopped vegetables, and Graeme said “You’re a pro.”",
		},
	},
	{
		english: "Egg",
		romaji: "tamago",
		hiragana: "たまご",
		kanji: "卵",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "グレームは卵を割って、リノは「上手！」と言いました。",
			romaji: "Gureemu wa tamago o watte, Rino wa \"Jouzu!\" to iimashita.",
			english: "Graeme cracked an egg, and Rino said “Nice!”",
		},
	},
	{
		english: "Milk",
		romaji: "gyuunyuu",
		hiragana: "ぎゅうにゅう",
		kanji: "牛乳",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "リノは牛乳を入れて、グレームは「まろやか」と言いました。",
			romaji: "Rino wa gyuunyuu o irete, Gureemu wa \"Maroyaka\" to iimashita.",
			english: "Rino added milk, and Graeme said “So smooth.”",
		},
	},
	{
		english: "Sugar",
		romaji: "satou",
		hiragana: "さとう",
		kanji: "砂糖",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "グレームが砂糖を入れすぎて、リノは「甘い！」と言いました。",
			romaji: "Gureemu ga satou o iresugite, Rino wa \"Amai!\" to iimashita.",
			english: "Graeme added too much sugar, and Rino said “Sweet!”",
		},
	},
	{
		english: "Salt",
		romaji: "shio",
		hiragana: "しお",
		kanji: "塩",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "リノは塩を少し入れて、グレームは「ちょうどいい」と言いました。",
			romaji: "Rino wa shio o sukoshi irete, Gureemu wa \"Choudo ii\" to iimashita.",
			english: "Rino added a little salt, and Graeme said “Perfect.”",
		},
	},
	{
		english: "Spicy",
		romaji: "karai",
		hiragana: "からい",
		kanji: "辛い",
		partOfSpeech: "i-adjective",
		jlpt: "N5",
		example: {
			japanese: "このカレーは辛いので、グレームとリノは水を飲みました。",
			romaji: "Kono karee wa karai no de, Gureemu to Rino wa mizu o nomimashita.",
			english: "This curry is spicy, so Graeme and Rino drank water.",
		},
	},
	{
		english: "Sweet",
		romaji: "amai",
		hiragana: "あまい",
		kanji: "甘い",
		partOfSpeech: "i-adjective",
		jlpt: "N5",
		example: {
			japanese: "ケーキが甘くて、リノは幸せで、グレームはニヤニヤしました。",
			romaji: "Keeki ga amakute, Rino wa shiawase de, Gureemu wa niyaniya shimashita.",
			english: "The cake was sweet; Rino was happy and Graeme grinned.",
		},
	},
	{
		english: "Sour",
		romaji: "suppai",
		hiragana: "すっぱい",
		kanji: "酸っぱい",
		partOfSpeech: "i-adjective",
		jlpt: "N4",
		example: {
			japanese: "すっぱいレモンを食べて、グレームとリノは変な顔をしました。",
			romaji: "Suppai remon o tabete, Gureemu to Rino wa hen na kao o shimashita.",
			english: "They ate a sour lemon, and Graeme and Rino made funny faces.",
		},
	},
	{
		english: "Hot (food)",
		romaji: "atsui",
		hiragana: "あつい",
		kanji: "熱い",
		partOfSpeech: "i-adjective",
		jlpt: "N5",
		example: {
			japanese: "スープが熱くて、リノは「ふーふーして」とグレームに言いました。",
			romaji: "Suupu ga atsukute, Rino wa \"Fuu-fuu shite\" to Gureemu ni iimashita.",
			english: "The soup was hot, and Rino told Graeme “Blow on it.”",
		},
	},
	{
		english: "Cold (drink/food)",
		romaji: "tsumetai",
		hiragana: "つめたい",
		kanji: "冷たい",
		partOfSpeech: "i-adjective",
		jlpt: "N5",
		example: {
			japanese: "水が冷たくて、グレームは「最高！」と言い、リノは笑いました。",
			romaji: "Mizu ga tsumetakute, Gureemu wa \"Saikou!\" to ii, Rino wa waraimashita.",
			english: "The water was cold, and Graeme said “Perfect!” while Rino laughed.",
		},
	},
	{
		english: "Good",
		romaji: "ii",
		hiragana: "いい",
		kanji: "良い",
		partOfSpeech: "i-adjective",
		jlpt: "N5",
		example: {
			japanese: "リノは「いいね」と言って、グレームはガッツポーズしました。",
			romaji: "Rino wa \"Ii ne\" to itte, Gureemu wa gattsu poozu shimashita.",
			english: "Rino said “Nice,” and Graeme fist-pumped.",
		},
	},
	{
		english: "Bad",
		romaji: "warui",
		hiragana: "わるい",
		kanji: "悪い",
		partOfSpeech: "i-adjective",
		jlpt: "N5",
		example: {
			japanese: "天気が悪くて、グレームとリノは家にいました。",
			romaji: "Tenki ga warukute, Gureemu to Rino wa ie ni imashita.",
			english: "The weather was bad, so Graeme and Rino stayed home.",
		},
	},
	{
		english: "Big",
		romaji: "ookii",
		hiragana: "おおきい",
		kanji: "大きい",
		partOfSpeech: "i-adjective",
		jlpt: "N5",
		example: {
			japanese: "グレームは大きいコーヒーを選んで、リノは「眠れないよ」と言いました。",
			romaji:
				"Gureemu wa ookii koohii o erande, Rino wa \"Nemurenai yo\" to iimashita.",
			english: "Graeme chose a big coffee, and Rino said “You won’t sleep.”",
		},
	},
	{
		english: "Small",
		romaji: "chiisai",
		hiragana: "ちいさい",
		kanji: "小さい",
		partOfSpeech: "i-adjective",
		jlpt: "N5",
		example: {
			japanese: "リノのかばんは小さくて、グレームは「魔法？」と言いました。",
			romaji: "Rino no kaban wa chiisakute, Gureemu wa \"Mahou?\" to iimashita.",
			english: "Rino’s bag is small, and Graeme said “Magic?”",
		},
	},
	{
		english: "New",
		romaji: "atarashii",
		hiragana: "あたらしい",
		kanji: "新しい",
		partOfSpeech: "i-adjective",
		jlpt: "N5",
		example: {
			japanese: "グレームは新しい靴を買って、リノは「かっこいい」と言いました。",
			romaji: "Gureemu wa atarashii kutsu o katte, Rino wa \"Kakkoii\" to iimashita.",
			english: "Graeme bought new shoes, and Rino said “Cool.”",
		},
	},
	{
		english: "Old",
		romaji: "furui",
		hiragana: "ふるい",
		kanji: "古い",
		partOfSpeech: "i-adjective",
		jlpt: "N5",
		example: {
			japanese: "古い本を見て、リノは「いい味だね」と言い、グレームはうなずきました。",
			romaji:
				"Furui hon o mite, Rino wa \"Ii aji da ne\" to ii, Gureemu wa unazukimashita.",
			english: "Seeing an old book, Rino said “It has character,” and Graeme agreed.",
		},
	},
	{
		english: "Interesting",
		romaji: "omoshiroi",
		hiragana: "おもしろい",
		kanji: "面白い",
		partOfSpeech: "i-adjective",
		jlpt: "N5",
		example: {
			japanese: "この映画は面白いと、グレームが言って、リノも笑いました。",
			romaji: "Kono eiga wa omoshiroi to, Gureemu ga itte, Rino mo waraimashita.",
			english: "Graeme said this movie is interesting, and Rino laughed too.",
		},
	},
	{
		english: "Boring",
		romaji: "tsumaranai",
		hiragana: "つまらない",
		partOfSpeech: "i-adjective",
		jlpt: "N4",
		example: {
			japanese: "グレームが「つまらない…」と言って、リノは「じゃあ散歩！」と言いました。",
			romaji:
				"Gureemu ga \"Tsumaranai...\" to itte, Rino wa \"Jaa sanpo!\" to iimashita.",
			english: "Graeme said “I’m bored…,” and Rino said “Then let’s walk!”",
		},
	},
	{
		english: "Fun",
		romaji: "tanoshii",
		hiragana: "たのしい",
		kanji: "楽しい",
		partOfSpeech: "i-adjective",
		jlpt: "N5",
		example: {
			japanese: "旅行は楽しいと、リノが言って、グレームも同意しました。",
			romaji: "Ryokou wa tanoshii to, Rino ga itte, Gureemu mo doui shimashita.",
			english: "Rino said traveling is fun, and Graeme agreed.",
		},
	},
	{
		english: "Busy",
		romaji: "isogashii",
		hiragana: "いそがしい",
		kanji: "忙しい",
		partOfSpeech: "i-adjective",
		jlpt: "N5",
		example: {
			japanese: "リノは忙しくて、グレームは「手伝う？」と聞きました。",
			romaji: "Rino wa isogashikute, Gureemu wa \"Tetsudau?\" to kikimashita.",
			english: "Rino was busy, and Graeme asked “Want help?”",
		},
	},
	{
		english: "Free time / not busy",
		romaji: "hima",
		hiragana: "ひま",
		kanji: "暇",
		partOfSpeech: "na-adjective",
		jlpt: "N5",
		example: {
			japanese: "グレームが「暇だ…」と言って、リノは「勉強しよう」と言いました。",
			romaji: "Gureemu ga \"Hima da...\" to itte, Rino wa \"Benkyou shiyou\" to iimashita.",
			english: "Graeme said “I’m free…,” and Rino said “Let’s study.”",
		},
	},
	{
		english: "Easy / simple",
		romaji: "kantan",
		hiragana: "かんたん",
		kanji: "簡単",
		partOfSpeech: "na-adjective",
		jlpt: "N5",
		example: {
			japanese: "リノは「簡単だよ」と言って、グレームは安心しました。",
			romaji: "Rino wa \"Kantan da yo\" to itte, Gureemu wa anshin shimashita.",
			english: "Rino said “It’s easy,” and Graeme felt relieved.",
		},
	},
	{
		english: "Difficult",
		romaji: "muzukashii",
		hiragana: "むずかしい",
		kanji: "難しい",
		partOfSpeech: "i-adjective",
		jlpt: "N5",
		example: {
			japanese: "漢字は難しいと、グレームが言って、リノは「少しずつ」と言いました。",
			romaji: "Kanji wa muzukashii to, Gureemu ga itte, Rino wa \"Sukoshi zutsu\" to iimashita.",
			english: "Graeme said kanji is difficult, and Rino said “Little by little.”",
		},
	},
	{
		english: "Expensive / high",
		romaji: "takai",
		hiragana: "たかい",
		kanji: "高い",
		partOfSpeech: "i-adjective",
		jlpt: "N5",
		example: {
			japanese: "このホテルは高いと、リノが言って、グレームは「スコットランドより？」と聞きました。",
			romaji:
				"Kono hoteru wa takai to, Rino ga itte, Gureemu wa \"Sukottorando yori?\" to kikimashita.",
			english: "Rino said this hotel is expensive, and Graeme asked “More than Scotland?”",
		},
	},
	{
		english: "Cheap",
		romaji: "yasui",
		hiragana: "やすい",
		kanji: "安い",
		partOfSpeech: "i-adjective",
		jlpt: "N5",
		example: {
			japanese: "この店は安いので、グレームとリノはたくさん買いました。",
			romaji: "Kono mise wa yasui no de, Gureemu to Rino wa takusan kaimashita.",
			english: "This shop is cheap, so Graeme and Rino bought a lot.",
		},
	},
	{
		english: "Fast / early",
		romaji: "hayai",
		hiragana: "はやい",
		kanji: "早い",
		partOfSpeech: "i-adjective",
		jlpt: "N5",
		example: {
			japanese: "リノは「早いね」と言って、グレームは得意げでした。",
			romaji: "Rino wa \"Hayai ne\" to itte, Gureemu wa tokuige deshita.",
			english: "Rino said “That was fast,” and Graeme looked proud.",
		},
	},
	{
		english: "Slow / late",
		romaji: "osoi",
		hiragana: "おそい",
		kanji: "遅い",
		partOfSpeech: "i-adjective",
		jlpt: "N5",
		example: {
			japanese: "グレームが遅くて、リノは「置いてくよ！」と言いました。",
			romaji: "Gureemu ga osokute, Rino wa \"Oiteku yo!\" to iimashita.",
			english: "Graeme was late, and Rino said “I’m leaving you behind!”",
		},
	},
	{
		english: "Hot (weather)",
		romaji: "atsui",
		hiragana: "あつい",
		kanji: "暑い",
		partOfSpeech: "i-adjective",
		jlpt: "N5",
		example: {
			japanese: "今日は暑くて、グレームとリノはアイスを買いました。",
			romaji: "Kyou wa atsukute, Gureemu to Rino wa aisu o kaimashita.",
			english: "It’s hot today, so Graeme and Rino bought ice cream.",
		},
	},
	{
		english: "Cold (weather)",
		romaji: "samui",
		hiragana: "さむい",
		kanji: "寒い",
		partOfSpeech: "i-adjective",
		jlpt: "N5",
		example: {
			japanese: "北海道は寒いので、リノは「上着！」とグレームに言いました。",
			romaji: "Hokkaidou wa samui no de, Rino wa \"Uwagi!\" to Gureemu ni iimashita.",
			english: "Because Hokkaido is cold, Rino told Graeme “Jacket!”",
		},
	},
	{
		english: "Warm",
		romaji: "atatakai",
		hiragana: "あたたかい",
		kanji: "暖かい",
		partOfSpeech: "i-adjective",
		jlpt: "N5",
		example: {
			japanese: "お茶が暖かくて、グレームとリノはほっとしました。",
			romaji: "Ocha ga atatakakute, Gureemu to Rino wa hotto shimashita.",
			english: "The tea was warm, and Graeme and Rino relaxed.",
		},
	},
	{
		english: "Cool (weather)",
		romaji: "suzushii",
		hiragana: "すずしい",
		kanji: "涼しい",
		partOfSpeech: "i-adjective",
		jlpt: "N5",
		example: {
			japanese: "夕方は涼しくて、グレームとリノは散歩しました。",
			romaji: "Yuugata wa suzushikute, Gureemu to Rino wa sanpo shimashita.",
			english: "It was cool in the evening, so Graeme and Rino took a walk.",
		},
	},
	{
		english: "Beautiful / clean",
		romaji: "kirei",
		hiragana: "きれい",
		kanji: "綺麗",
		partOfSpeech: "na-adjective",
		jlpt: "N5",
		example: {
			japanese: "横浜の夜景はきれいで、グレームとリノは写真を撮りました。",
			romaji: "Yokohama no yakei wa kirei de, Gureemu to Rino wa shashin o torimashita.",
			english: "Yokohama’s night view was beautiful, so Graeme and Rino took photos.",
		},
	},
	{
		english: "Quiet",
		romaji: "shizuka",
		hiragana: "しずか",
		kanji: "静か",
		partOfSpeech: "na-adjective",
		jlpt: "N5",
		example: {
			japanese: "この部屋は静かで、リノは「最高」と言い、グレームはうなずきました。",
			romaji:
				"Kono heya wa shizuka de, Rino wa \"Saikou\" to ii, Gureemu wa unazukimashita.",
			english: "This room is quiet; Rino said “Perfect,” and Graeme agreed.",
		},
	},
	{
		english: "Noisy",
		romaji: "urusai",
		hiragana: "うるさい",
		partOfSpeech: "i-adjective",
		jlpt: "N5",
		example: {
			japanese: "外がうるさくて、グレームとリノは窓を閉めました。",
			romaji: "Soto ga urusakute, Gureemu to Rino wa mado o shimemashita.",
			english: "It was noisy outside, so Graeme and Rino closed the window.",
		},
	},
	{
		english: "Scary",
		romaji: "kowai",
		hiragana: "こわい",
		kanji: "怖い",
		partOfSpeech: "i-adjective",
		jlpt: "N5",
		example: {
			japanese: "リノは「こわい」と言って、グレームのうしろに隠れました。",
			romaji: "Rino wa \"Kowai\" to itte, Gureemu no ushiro ni kakuremashita.",
			english: "Rino said “I’m scared” and hid behind Graeme.",
		},
	},
	{
		english: "Happy / glad",
		romaji: "ureshii",
		hiragana: "うれしい",
		kanji: "嬉しい",
		partOfSpeech: "i-adjective",
		jlpt: "N5",
		example: {
			japanese: "プレゼントをもらって、リノはうれしくて、グレームもにこにこしました。",
			romaji: "Purezento o moratte, Rino wa ureshikute, Gureemu mo niko-niko shimashita.",
			english: "Rino got a present and was happy; Graeme smiled too.",
		},
	},
	{
		english: "Sad",
		romaji: "kanashii",
		hiragana: "かなしい",
		kanji: "悲しい",
		partOfSpeech: "i-adjective",
		jlpt: "N5",
		example: {
			japanese: "映画が悲しくて、グレームとリノはティッシュを探しました。",
			romaji: "Eiga ga kanashikute, Gureemu to Rino wa tisshu o sagashimashita.",
			english: "The movie was sad, and Graeme and Rino looked for tissues.",
		},
	},
	{
		english: "Convenient",
		romaji: "benri",
		hiragana: "べんり",
		kanji: "便利",
		partOfSpeech: "na-adjective",
		jlpt: "N4",
		example: {
			japanese: "このアプリは便利だと、リノが言って、グレームはすぐ入れました。",
			romaji: "Kono apuri wa benri da to, Rino ga itte, Gureemu wa sugu iremashita.",
			english: "Rino said this app is convenient, and Graeme installed it right away.",
		},
	},
	{
		english: "Necessary",
		romaji: "hitsuyou",
		hiragana: "ひつよう",
		kanji: "必要",
		partOfSpeech: "na-adjective",
		jlpt: "N4",
		example: {
			japanese: "パスポートは必要だと、リノが言って、グレームはポケットを確認しました。",
			romaji:
				"Pasupooto wa hitsuyou da to, Rino ga itte, Gureemu wa poketto o kakunin shimashita.",
			english: "Rino said a passport is necessary, and Graeme checked his pocket.",
		},
	},
	{
		english: "Important",
		romaji: "taisetsu",
		hiragana: "たいせつ",
		kanji: "大切",
		partOfSpeech: "na-adjective",
		jlpt: "N4",
		example: {
			japanese: "リノは「これは大切」と言って、グレームは大事に持ちました。",
			romaji: "Rino wa \"Kore wa taisetsu\" to itte, Gureemu wa daiji ni mochimashita.",
			english: "Rino said “This is important,” and Graeme held it carefully.",
		},
	},
	{
		english: "Safe",
		romaji: "anzen",
		hiragana: "あんぜん",
		kanji: "安全",
		partOfSpeech: "na-adjective",
		jlpt: "N4",
		example: {
			japanese: "リノは「安全だよ」と言って、グレームは安心しました。",
			romaji: "Rino wa \"Anzen da yo\" to itte, Gureemu wa anshin shimashita.",
			english: "Rino said “It’s safe,” and Graeme relaxed.",
		},
	},
	{
		english: "Dangerous",
		romaji: "abunai",
		hiragana: "あぶない",
		kanji: "危ない",
		partOfSpeech: "i-adjective",
		jlpt: "N4",
		example: {
			japanese: "リノは「危ない！」と言って、グレームのうでを引きました。",
			romaji: "Rino wa \"Abunai!\" to itte, Gureemu no ude o hikimashita.",
			english: "Rino yelled “Danger!” and pulled Graeme’s arm.",
		},
	},
	{
		english: "Problem",
		romaji: "mondai",
		hiragana: "もんだい",
		kanji: "問題",
		partOfSpeech: "noun",
		jlpt: "N4",
		example: {
			japanese: "問題があって、グレームは困って、リノは助けました。",
			romaji: "Mondai ga atte, Gureemu wa komatte, Rino wa tasukemashita.",
			english: "There was a problem; Graeme struggled and Rino helped.",
		},
	},
	{
		english: "Preparation",
		romaji: "junbi",
		hiragana: "じゅんび",
		kanji: "準備",
		partOfSpeech: "noun",
		jlpt: "N4",
		example: {
			japanese: "北海道旅行の準備をして、グレームとリノはわくわくしました。",
			romaji: "Hokkaidou ryokou no junbi o shite, Gureemu to Rino wa wakuwaku shimashita.",
			english: "Preparing for a Hokkaido trip, Graeme and Rino got excited.",
		},
	},
	{
		english: "Practice",
		romaji: "renshuu",
		hiragana: "れんしゅう",
		kanji: "練習",
		partOfSpeech: "noun",
		jlpt: "N4",
		example: {
			japanese: "毎日練習して、グレームとリノは上手になりました。",
			romaji: "Mainichi renshuu shite, Gureemu to Rino wa jouzu ni narimashita.",
			english: "They practiced every day, and Graeme and Rino improved.",
		},
	},
	{
		english: "To decide",
		romaji: "kimeru",
		hiragana: "きめる",
		kanji: "決める",
		partOfSpeech: "verb",
		jlpt: "N4",
		example: {
			japanese: "行き先を決めて、リノは「横浜！」と言い、グレームは「北海道！」と言いました。",
			romaji:
				"Ikisaki o kimete, Rino wa \"Yokohama!\" to ii, Gureemu wa \"Hokkaidou!\" to iimashita.",
			english: "They decided the destination: Rino said “Yokohama!” and Graeme said “Hokkaido!”",
		},
	},
	{
		english: "To confirm / check",
		romaji: "kakunin suru",
		hiragana: "かくにんする",
		kanji: "確認する",
		partOfSpeech: "verb",
		jlpt: "N4",
		example: {
			japanese: "リノは予約を確認して、グレームは「完璧」と言いました。",
			romaji: "Rino wa yoyaku o kakunin shite, Gureemu wa \"Kanpeki\" to iimashita.",
			english: "Rino confirmed the reservation, and Graeme said “Perfect.”",
		},
	},
	{
		english: "Recommendation",
		romaji: "osusume",
		hiragana: "おすすめ",
		partOfSpeech: "noun",
		jlpt: "N4",
		example: {
			japanese: "リノのおすすめはラーメンで、グレームは即決しました。",
			romaji: "Rino no osusume wa raamen de, Gureemu wa sokketsu shimashita.",
			english: "Rino’s recommendation was ramen, and Graeme decided instantly.",
		},
	},
	{
		english: "Trip / travel",
		romaji: "ryokou",
		hiragana: "りょこう",
		kanji: "旅行",
		partOfSpeech: "noun",
		jlpt: "N4",
		example: {
			japanese: "北海道旅行の話で、グレームとリノは盛り上がりました。",
			romaji: "Hokkaidou ryokou no hanashi de, Gureemu to Rino wa moriagarimashita.",
			english: "Talking about a Hokkaido trip, Graeme and Rino got hyped.",
		},
	},
	{
		english: "Souvenir",
		romaji: "omiyage",
		hiragana: "おみやげ",
		kanji: "お土産",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "グレームはお土産を買って、リノは「センスいい！」と言いました。",
			romaji: "Gureemu wa omiyage o katte, Rino wa \"Sensu ii!\" to iimashita.",
			english: "Graeme bought souvenirs, and Rino said “Great taste!”",
		},
	},
	{
		english: "Weather",
		romaji: "tenki",
		hiragana: "てんき",
		kanji: "天気",
		partOfSpeech: "noun",
		jlpt: "N5",
		example: {
			japanese: "天気を見て、リノは「雨」、グレームは「傘！」と言いました。",
			romaji: "Tenki o mite, Rino wa \"Ame\", Gureemu wa \"Kasa!\" to iimashita.",
			english: "Checking the weather, Rino said “Rain,” and Graeme said “Umbrella!”",
		},
	},
];
