import { PreSatori } from "@/utils/pre-satori";

interface BabyProps {
	width?: number;
	height?: number;
}

const START_DATE = new Date("2025-12-08T00:00:00");
const END_DATE = new Date("2026-09-14T00:00:00");

// Week-by-week pregnancy updates (general info; individual timelines vary).
// Source note: This is a plain-language summary for an app UI, not medical advice.

const pregnancyWeekUpdate: Record<number, string> = {
	1: "Your body is preparing for ovulation; pregnancy usually hasn’t started yet.",
	2: "Ovulation is approaching or happening; fertilisation can occur near the end of this week.",
	3: "Fertilisation may occur and the tiny cluster of cells begins dividing as it travels to the uterus.",
	4: "Implantation often happens; early hormone (hCG) rises and a missed period may be near.",
	5: "The embryo is growing fast; the neural tube begins forming and the heart is starting to develop.",
	6: "Early heartbeat activity may be detectable on ultrasound; limb buds start appearing.",
	7: "The brain and spinal cord develop rapidly; arms/legs lengthen and facial features begin shaping.",
	8: "Major organs are forming; fingers and toes start to separate; movement begins (too small to feel).",
	9: "Now called a fetus; basic body plan is in place and tiny muscles can make small movements.",
	10: "Bones begin hardening; nails and tooth buds start forming; many people hear a heartbeat at visits.",
	11: "Facial features refine; the fetus can stretch and kick; external genitals begin developing.",
	12: "Reflexes emerge; the placenta takes on more of the work supporting growth.",
	13: "Second trimester begins; vocal cords form and the fetus can make more coordinated movements.",
	14: "Fine facial details sharpen; early hair patterns start; the fetus can practise expressions.",
	15: "Hearing structures develop; the fetus may respond to sound/vibration in subtle ways.",
	16: "Some people start feeling ‘flutters’; limbs are stronger and head/neck control improves.",
	17: "Fat stores begin forming; the umbilical cord and placenta are supplying nutrients efficiently.",
	18: "Kicks may become noticeable; ears are positioned and hearing continues to mature.",
	19: "Skin is protected by vernix; senses are developing and movements get more regular.",
	20: "Halfway point; many anatomy scans happen around now and movements are often clearer.",
	21: "The fetus practises swallowing; digestive system continues maturing and activity cycles form.",
	22: "Eyebrows and eyelashes become more visible; grip strength and startle reflex develop.",
	23: "Lungs develop air sacs; the fetus responds more consistently to sound and touch.",
	24: "Rapid brain growth; lungs and skin continue maturing; viability discussions often start here.",
	25: "More predictable sleep/wake rhythm; the fetus may startle at loud noises.",
	26: "Eyes may begin opening; lungs keep developing and coordinated sucking practice can begin.",
	27: "Third trimester begins; brain and nervous system ramp up and growth accelerates.",
	28: "Blink reflex appears; fat increases and the fetus may settle into a more consistent position.",
	29: "Stronger kicks and stretches; muscles and lungs keep maturing; head growth continues.",
	30: "Brain develops more folds and grooves; the fetus practises breathing-like motions.",
	31: "Rapid brain development; movements can be strong and rhythmic (including hiccups).",
	32: "Bones are formed but still soft; the fetus gains fat and practises breathing and swallowing.",
	33: "Immune support increases; the fetus may turn head-down (but can still change position).",
	34: "Lungs are maturing quickly; many babies are head-down now and weight gain speeds up.",
	35: "The fetus fills more of the uterus, so movements may feel bigger but less ‘spinny’.",
	36: "Often ‘nearly term’; the fetus may drop lower in the pelvis and practises sucking and breathing.",
	37: "Early term; organs are ready to function outside and fat stores keep building.",
	38: "The fetus continues to gain weight; hair and skin features mature and movements remain important.",
	39: "Full term; the fetus is usually in final position and getting ready for birth.",
	40: "Due week; the baby is fully developed—labour may start any day (and ‘overdue’ can be normal).",
};

// Size comparisons by week (rough, for fun; varies a lot person-to-person).
// Intended for UI display (e-ink friendly one-liners).

export const pregnancySizeComparisonByDay: Record<number, string> = {
	1: "Calendar dot",
	2: "Pencil point",
	3: "Pinhead",
	4: "Paper fibre",
	5: "Speck of dust",
	6: "Salt flake",
	7: "Sugar grain",
	8: "Tiny ink spot",
	9: "Needle tip",
	10: "Glitter fleck",
	11: "Shortbread crumb",
	12: "Wee breadcrumb",
	13: "Sesame flake",
	14: "Goma (sesame seed)",
	15: "Two sesame seeds",
	16: "Poppy seed",
	17: "Mustard seed",
	18: "Millet grain",
	19: "Grain of rice",
	20: "Half-grain of rice",
	21: "Chia seed",
	22: "Tiny bead",
	23: "Micro button",
	24: "Apple seed",
	25: "Plump apple seed",
	26: "Peppercorn",
	27: "Pink peppercorn",
	28: "Juniper berry",
	29: "Wee lentil",
	30: "Lentil",
	31: "Red lentil",
	32: "Split pea",
	33: "Yellow split pea",
	34: "Two capers",
	35: "Caper",
	36: "Garden pea",
	37: "Plump pea",
	38: "Blueberry",
	39: "Large blueberry",
	40: "Small strawberry",
	41: "Plump raspberry",
	42: "Wee grape",
	43: "Strawberry",
	44: "Blackberry",
	45: "Wee grape",
	46: "Grape",
	47: "Large grape",
	48: "Cherry",
	49: "Two cherries",
	50: "Olive",
	51: "Green olive",
	52: "Kalamata olive",
	53: "Kumquat",
	54: "Biwa (loquat)",
	55: "Large biwa (loquat)",
	56: "Raisin",
	57: "Currant",
	58: "Sultana",
	59: "Raisin",
	60: "Wee grape",
	61: "Olive",
	62: "Wee cherry",
	63: "Grape",
	64: "Cherry",
	65: "Wee strawberry",
	66: "Strawberry",
	67: "Kumquat",
	68: "Biwa (loquat)",
	69: "Wee ume (plum)",
	70: "Wee apricot",
	71: "Apricot",
	72: "Wee yuzu (citrus)",
	73: "Yuzu (citrus)",
	74: "Wee mikan (satsuma/mandarin)",
	75: "Mikan (satsuma/mandarin)",
	76: "Wee lime",
	77: "Lime",
	78: "Wee lemon",
	79: "Lemon",
	80: "Kiwi fruit",
	81: "Large kiwi fruit",
	82: "Wee peach",
	83: "Peach",
	84: "Wee apple",
	85: "Apple",
	86: "Large apple",
	87: "Wee avocado",
	88: "Avocado",
	89: "Large avocado",
	90: "Wee nashi (Asian pear)",
	91: "Nashi (Asian pear)",
	92: "Wee pear",
	93: "Pear",
	94: "Wee onigiri (rice ball)",
	95: "Onigiri (rice ball)",
	96: "Wee tennis ball",
	97: "Tennis ball",
	98: "Wee softball",
	99: "Softball",
	100: "Small mango",
	101: "Mango",
	102: "Large mango",
	103: "Paprika (bell pepper)",
	104: "Large bell pepper",
	105: "Beefsteak tomato",
	106: "Large tomato",
	107: "Small pomegranate",
	108: "Pomegranate",
	109: "Large pomegranate",
	110: "Small onion",
	111: "Onion",
	112: "Large onion",
	113: "Small sweet potato",
	114: "Sweet potato",
	115: "Large sweet potato",
	116: "Small turnip",
	117: "Turnip",
	118: "Large turnip",
	119: "Small swede (neeps)",
	120: "Swede (neeps)",
	121: "Large swede (neeps)",
	122: "Large carrot",
	123: "Long carrot",
	124: "Chunky carrot",
	125: "Parsnip",
	126: "Large parsnip",
	127: "Courgette (zucchini)",
	128: "Large courgette (zucchini)",
	129: "Small nasu (aubergine)",
	130: "Nasu (aubergine)",
	131: "Large aubergine",
	132: "Small butternut squash",
	133: "Butternut squash",
	134: "Large butternut squash",
	135: "Short banana",
	136: "Banana",
	137: "Long banana",
	138: "Small papaya",
	139: "Papaya",
	140: "Large papaya",
	141: "Small cabbage",
	142: "Cabbage",
	143: "Large cabbage",
	144: "Small cauliflower",
	145: "Cauliflower",
	146: "Large cauliflower",
	147: "Broccoli head",
	148: "Large broccoli",
	149: "Small kabocha (Japanese pumpkin)",
	150: "Kabocha (Japanese pumpkin)",
	151: "Large kabocha",
	152: "Short corn cob",
	153: "Corn cob",
	154: "Large corn cob",
	155: "Large cucumber",
	156: "Long cucumber",
	157: "Bunch of spring onions",
	158: "Small bok choy",
	159: "Bok choy",
	160: "Large pak choi",
	161: "Small loaf of shokupan (milk bread)",
	162: "Loaf of shokupan (milk bread)",
	163: "Large loaf of shokupan (milk bread)",
	164: "Small ramen bowl",
	165: "Ramen bowl",
	166: "Hefty ramen bowl",
	167: "Small bento box",
	168: "Bento box",
	169: "Large bento box",
	170: "Thin paperback book",
	171: "Paperback book",
	172: "Thick paperback book",
	173: "Wee hardback book",
	174: "Hardback book",
	175: "Thick hardback book",
	176: "Small football (size 2)",
	177: "Football (size 3)",
	178: "Football (size 4)",
	179: "Small coconut",
	180: "Coconut",
	181: "Large coconut",
	182: "Small pumpkin",
	183: "Pumpkin",
	184: "Large pumpkin",
	185: "Hefty cantaloupe melon",
	186: "Very hefty cantaloupe melon",
	187: "Wee honeydew",
	188: "Medium honeydew",
	189: "Plump honeydew",
	190: "Wee small watermelon",
	191: "Round small watermelon",
	192: "Wee watermelon",
	193: "Small pineapple",
	194: "Pineapple",
	195: "Large pineapple",
	196: "Small honeydew melon",
	197: "Honeydew melon",
	198: "Large honeydew",
	199: "Small watermelon",
	200: "Watermelon",
	201: "Large watermelon",
	202: "Wee basketball",
	203: "Basketball",
	204: "Large basketball",
	205: "Small yoga ball",
	206: "Yoga ball",
	207: "Large yoga ball",
	208: "Small cushion",
	209: "Cushion",
	210: "Large cushion",
	211: "Small pillow",
	212: "Pillow",
	213: "Large pillow",
	214: "Small beanbag",
	215: "Beanbag",
	216: "Large beanbag",
	217: "Small laundry basket",
	218: "Laundry basket",
	219: "Large laundry basket",
	220: "Small duffel bag",
	221: "Duffel bag",
	222: "Large duffel bag",
	223: "Wee shoebox",
	224: "Shoebox",
	225: "Large shoebox",
	226: "Small picnic basket",
	227: "Picnic basket",
	228: "Large picnic basket",
	229: "Small mixing bowl",
	230: "Mixing bowl",
	231: "Large mixing bowl",
	232: "Small stockpot",
	233: "Stockpot",
	234: "Large stockpot",
	235: "Small kettle",
	236: "Kettle",
	237: "Large kettle",
	238: "Small toaster",
	239: "Toaster",
	240: "Large toaster",
	241: "Small rice cooker pot",
	242: "Rice cooker pot",
	243: "Full rice cooker pot",
	244: "Small casserole dish",
	245: "Casserole dish",
	246: "Large casserole dish",
	247: "Small beach ball",
	248: "Beach ball",
	249: "Large beach ball",
	250: "Tatami cushion (zabuton)",
	251: "Plump zabuton",
	252: "Extra plump zabuton",
	253: "Football (size 5)",
	254: "Rugby ball",
	255: "Full-size rugby ball",
	256: "Wee bowling ball",
	257: "Bowling ball",
	258: "Hefty bowling ball",
	259: "Heavy large melon",
	260: "Very heavy large melon",
	261: "Huge heavy melon",
	262: "Heavy small pumpkin",
	263: "Heavy pumpkin",
	264: "Heavy large pumpkin",
	265: "Heavy small watermelon",
	266: "Heavy watermelon",
	267: "Heavy large watermelon",
	268: "Small tea tin",
	269: "Tea tin",
	270: "Large tea tin",
	271: "Wee biscuit tin",
	272: "Biscuit tin",
	273: "Large biscuit tin",
	274: "Small rucksack",
	275: "Rucksack",
	276: "Final-stretch watermelon",
	277: "Nearly-there watermelon",
	278: "Due-day watermelon",
	279: "Big due-day watermelon",
	280: "Average due-day watermelon",
};

export const pregnancyNameSuggestionByDay: Record<number, string> = {
	1: "Anna",
	2: "Mia",
	3: "Emma",
	4: "Sara",
	5: "Maya",
	6: "Nina",
	7: "Erika",
	8: "Naomi",
	9: "Mika",
	10: "Mari",
	11: "Rina",
	12: "Ami",
	13: "Yuna",
	14: "Hana",
	15: "Aya",
	16: "Mei",
	17: "Mai",
	18: "Yuri",
	19: "Yuki",
	20: "Sora",
	21: "Rei",
	22: "Ren",
	23: "Kai",
	24: "Leo",
	25: "Noah",
	26: "Liam",
	27: "Alex",
	28: "Sam",
	29: "Ben",
	30: "Max",
	31: "Tom",
	32: "Dan",
	33: "Luke",
	34: "Jack",
	35: "Jamie",
	36: "Robin",
	37: "Morgan",
	38: "Casey",
	39: "Rowan",
	40: "Rory",
	41: "Logan",
	42: "Cameron",
	43: "Ewan",
	44: "Callum",
	45: "Finlay",
	46: "Keira",
	47: "Cara",
	48: "Lara",
	49: "Leah",
	50: "Skye",
	51: "Isla",
	52: "Iona",
	53: "Fiona",
	54: "Mairi",
	55: "Aileen",
	56: "Eilidh",
	57: "Aoi",
	58: "Akira",
	59: "Haru",
	60: "Hiro",
	61: "Jun",
	62: "Rin",
	63: "Mio",
	64: "Miu",
	65: "Emi",
	66: "Ema",
	67: "Aki",
	68: "Nao",
	69: "Ryo",
	70: "Kyo",
	71: "Kei",
	72: "Rui",
	73: "Aria",
	74: "Ava",
	75: "Ella",
	76: "Lily",
	77: "Amy",
	78: "Kate",
	79: "Sophie",
	80: "Chloe",
	81: "Lucy",
	82: "Ruby",
	83: "Grace",
	84: "Clara",
	85: "Eva",
	86: "Lena",
	87: "Elena",
	88: "Maria",
	89: "Marie",
	90: "Iris",
	91: "Nora",
	92: "Elsa",
	93: "Alice",
	94: "Elise",
	95: "Serena",
	96: "Selena",
	97: "Rosa",
	98: "Tina",
	99: "Ria",
	100: "Rumi",
	101: "Remi",
	102: "Kira",
	103: "Hikari",
	104: "Hina",
	105: "Airi",
	106: "Saki",
	107: "Sana",
	108: "Riko",
	109: "Reina",
	110: "Minami",
	111: "Misaki",
	112: "Miki",
	113: "Maki",
	114: "Nana",
	115: "Nanami",
	116: "Sae",
	117: "Yui",
	118: "Yua",
	119: "Koharu",
	120: "Natsuki",
	121: "Makoto",
	122: "Hikaru",
	123: "Minato",
	124: "Satoshi",
	125: "Taichi",
	126: "Shota",
	127: "Haruto",
	128: "Haruki",
	129: "Kaito",
	130: "Kenta",
	131: "Kenji",
	132: "Keita",
	133: "Yuto",
	134: "Sota",
	135: "Riku",
	136: "Daiki",
	137: "Toma",
	138: "Rento",
	139: "Reo",
	140: "Kazu",
	141: "Toru",
	142: "Koji",
	143: "Ryota",
	144: "Ryosuke",
	145: "Taiga",
	146: "Ari",
	147: "Mina",
	148: "Noa",
	149: "Sora",
	150: "Yuki",
	151: "Ren",
	152: "Rei",
	153: "Kei",
	154: "Rui",
	155: "Mio",
	156: "Rin",
	157: "Aoi",
	158: "Akira",
	159: "Haru",
	160: "Hiro",
	161: "Jun",
	162: "Ryo",
	163: "Nao",
	164: "Emi",
	165: "Mei",
	166: "Aya",
	167: "Hana",
	168: "Yuna",
	169: "Mika",
	170: "Naomi",
	171: "Anna",
	172: "Mia",
	173: "Emma",
	174: "Sara",
	175: "Maya",
	176: "Nina",
	177: "Erika",
	178: "Naomi",
	179: "Mika",
	180: "Mari",
	181: "Rina",
	182: "Ami",
	183: "Yuna",
	184: "Hana",
	185: "Aya",
	186: "Mei",
	187: "Mai",
	188: "Yuri",
	189: "Yuki",
	190: "Sora",
	191: "Rei",
	192: "Ren",
	193: "Kai",
	194: "Leo",
	195: "Noah",
	196: "Liam",
	197: "Alex",
	198: "Sam",
	199: "Ben",
	200: "Max",
	201: "Tom",
	202: "Dan",
	203: "Luke",
	204: "Jack",
	205: "Jamie",
	206: "Robin",
	207: "Morgan",
	208: "Casey",
	209: "Rowan",
	210: "Rory",
	211: "Logan",
	212: "Cameron",
	213: "Ewan",
	214: "Callum",
	215: "Finlay",
	216: "Keira",
	217: "Cara",
	218: "Lara",
	219: "Leah",
	220: "Skye",
	221: "Isla",
	222: "Iona",
	223: "Fiona",
	224: "Mairi",
	225: "Aileen",
	226: "Eilidh",
	227: "Aoi",
	228: "Akira",
	229: "Haru",
	230: "Hiro",
	231: "Jun",
	232: "Rin",
	233: "Mio",
	234: "Miu",
	235: "Emi",
	236: "Ema",
	237: "Aki",
	238: "Nao",
	239: "Ryo",
	240: "Kyo",
	241: "Kei",
	242: "Rui",
	243: "Aria",
	244: "Ava",
	245: "Ella",
	246: "Lily",
	247: "Amy",
	248: "Kate",
	249: "Sophie",
	250: "Chloe",
	251: "Lucy",
	252: "Ruby",
	253: "Grace",
	254: "Clara",
	255: "Eva",
	256: "Lena",
	257: "Elena",
	258: "Maria",
	259: "Marie",
	260: "Iris",
	261: "Nora",
	262: "Elsa",
	263: "Alice",
	264: "Elise",
	265: "Serena",
	266: "Selena",
	267: "Rosa",
	268: "Tina",
	269: "Ria",
	270: "Rumi",
	271: "Remi",
	272: "Kira",
	273: "Hikari",
	274: "Hina",
	275: "Airi",
	276: "Saki",
	277: "Sana",
	278: "Riko",
	279: "Reina",
	280: "Minami",
	281: "Misaki",
	282: "Miki",
	283: "Maki",
	284: "Nana",
	285: "Nanami",
	286: "Sae",
	287: "Yui",
	288: "Yua",
	289: "Koharu",
	290: "Natsuki",
	291: "Makoto",
	292: "Hikaru",
	293: "Minato",
	294: "Satoshi",
	295: "Taichi",
	296: "Shota",
	297: "Haruto",
	298: "Haruki",
	299: "Kaito",
	300: "Kenta",
};

const nameSuggestions = Object.values(pregnancyNameSuggestionByDay).filter(
	(name) => typeof name === "string" && name.trim().length > 0,
);

function pickRandom<T>(items: T[]) {
	return items[Math.floor(Math.random() * items.length)];
}

function toStartOfDay(date: Date) {
	return new Date(date.getFullYear(), date.getMonth(), date.getDate());
}

function diffInDays(from: Date, to: Date) {
	const start = toStartOfDay(from).getTime();
	const end = toStartOfDay(to).getTime();
	const msPerDay = 24 * 60 * 60 * 1000;
	return Math.round((end - start) / msPerDay);
}

export default function Baby({ width = 800, height = 480 }: BabyProps) {
	const today = new Date();
	const totalDays = Math.max(0, diffInDays(START_DATE, END_DATE));
	const cookedDaysRaw = diffInDays(START_DATE, today);
	const cookedDays = Math.min(Math.max(cookedDaysRaw, 0), totalDays);
	const remainingDays = Math.max(totalDays - cookedDays, 0);
	const cookedWeeks = Math.floor(cookedDays / 7);
	const cookedExtraDays = cookedDays % 7;
	const remainingWeeks = Math.floor(remainingDays / 7);
	const remainingExtraDays = remainingDays % 7;
	const progress = totalDays > 0 ? cookedDays / totalDays : 0;
	const currentWeek = Math.min(Math.max(Math.floor(cookedDays / 7) + 1, 1), 40);
	const weekUpdate = pregnancyWeekUpdate[currentWeek];
	const weekSize = pregnancySizeComparisonByDay[cookedDays];
	const suggestedName = pickRandom(nameSuggestions);

	const progressPercent = Math.round(progress * 100);
	const barWidth = 280;
	const barHeight = 28;

	return (
		<PreSatori useDoubling={true} width={width} height={height}>
			<div className="flex h-full w-full flex-col bg-white p-6 text-black font-inter">
				<div className="flex items-center justify-between border-b-2 border-black pb-3">
					<div className="text-4xl">Baby Gino</div>
					<div className="text-xl"></div>
				</div>

				<div className="flex flex-1 items-start justify-between gap-6">
					<div className="flex flex-col gap-4 pt-6">
						<div className="text-5xl mt-2">
							<span className="font-semibold">{cookedWeeks}</span> Weeks {", "}
							<span className="font-semibold">{cookedExtraDays}</span> days Old
						</div>
						{weekUpdate && (
							<div className="text-2xl leading-snug mt-6">{weekUpdate}</div>
						)}
						{weekSize && (
							<div className="flex items-center gap-3 text-2xl leading-snug mt-6">
								<svg
									width="28"
									height="20"
									viewBox="0 0 28 20"
									aria-hidden="true"
								>
									<path
										d="M18.5 1.5C13 1.5 9.5 5 7.2 8.5C5.4 11.2 4 14.5 6.1 17C7.7 18.9 10.6 19 13.4 18.4C18.6 17.3 25.5 11.8 24.7 6.4C24.2 3.1 21.9 1.5 18.5 1.5Z"
										fill="#000000"
									/>
								</svg>
								<div>Size of a {weekSize}!</div>
							</div>
						)}
					</div>

					<div className="flex flex-col items-start gap-4 pt-6">
						<div className="text-3xl font-semibold">
							{progressPercent}% Cooked
						</div>
						<div
							className="border-4 border-black"
							style={{ width: barWidth, height: barHeight }}
						>
							<div
								className="bg-black h-full"
								style={{ width: `${progressPercent}%` }}
							/>
						</div>
						{suggestedName && (
							<div
								className="border-1 border-black rounded-md p-3 mt-22"
								style={{ width: barWidth }}
							>
								<div className="text-xl font-semibold">How about...</div>
								<div className="text-4xl font-semibold leading-none mt-1">
									{suggestedName}??
								</div>
							</div>
						)}
					</div>
				</div>
			</div>
		</PreSatori>
	);
}
