export const pregnancyDayUpdate: Record<number, string> = {
	1: "Day 1 of your cycle! Your body is preparing, though conception is still about two weeks away.",
	2: "The uterine lining is shedding, making way for a new, fresh lining to build up.",
	3: "Your hormones are at a low point, but they're about to start rising to prepare for ovulation.",
	4: "A good day to focus on nutrition. Folate, found in leafy greens, is crucial even at this early stage.",
	5: "Did you know? The first 'week' of pregnancy is technically part of your menstrual cycle.",
	6: "Your body is selecting the follicle that will release an egg this month. No pressure!",
	7: "One week down. Your body's internal clock is ticking along, right on schedule.",
	8: "Estrogen levels are starting to climb, which will trigger the thickening of the uterine lining.",
	9: "You might feel a bit more energetic today, thanks to rising hormones.",
	10: "Fun fact: An egg is the largest cell in the human body, about the size of a grain of sand.",
	11: "Ovulation is getting closer. This is the start of your fertile window.",
	12: "Consider this the 'waiting for the star' phase. The egg is almost ready for its debut.",
	13: "Today could be ovulation day! The egg is released and begins its journey down the fallopian tube.",
	14: "The 24-hour countdown begins! The egg is viable for about a day, waiting for fertilisation.",
	15: "If fertilisation occurred, a new life has begun! It's a single cell, called a zygote.",
	16: "The zygote is now dividing into more cells, becoming a morula, while travelling to the uterus.",
	17: "This tiny ball of cells is a marvel of nature, containing the complete blueprint for a new person.",
	18: "The journey continues. The morula is now a blastocyst and is searching for a place to implant.",
	19: "Implantation may begin today. The blastocyst starts to burrow into the plush uterine lining.",
	20: "You might experience tiny cramps or light spotting, which can be a sign of implantation.",
	21: "Implantation is complete! The cells that will become the placenta are starting to produce hCG.",
	22: "hCG, the pregnancy hormone, is now detectable in your bloodstream and urine.",
	23: "Your period is officially late. Time for a pregnancy test?",
	24: "A positive test! It's still very early, but a big journey has begun. Congratulations!",
	25: "The embryo is now about the size of a poppy seed.",
	26: "The amniotic sac and yolk sac have formed. The yolk sac provides early nutrients.",
	27: "The neural tube, the precursor to the brain and spinal cord, is starting to form.",
	28: "Four weeks in! The basic structures for every organ system are now in place.",
	29: "The heart is beginning to form as a simple tube-like structure. The first beats are near.",
	30: "Your little one is curled up like a 'C'. They are growing at an incredible rate.",
	31: "Arm and leg buds have appeared, though they look more like tiny paddles right now.",
	32: "Reminder: If you haven't already, now is a great time to start taking a prenatal vitamin.",
	33: "The placenta is developing, getting ready to take over hormone production and nutrient delivery.",
	34: "Baby is the size of a sesame seed. The heart may have started its first flickers of beating.",
	35: "The heart is now beating at a steady rhythm. It's a tiny but mighty drum.",
	36: "Facial features are starting to emerge, with dark spots where the eyes will be.",
	37: "The pits that will become ears are forming, and the tip of the nose is taking shape.",
	38: "Fun fact: Your baby's heart is beating about 110 times a minute.",
	39: "Morning sickness might be making an appearance. Small, frequent snacks can help.",
	40: "The umbilical cord is now distinct and is transferring oxygen and nutrients.",
	41: "An ultrasound might detect a heartbeat! It's a magical sound.",
	42: "At the end of week 6, your baby is the size of a lentil.",
	43: "Hands and feet are developing ridges that will soon become fingers and toes.",
	44: "The brain is growing rapidly, becoming more complex every day.",
	45: "Eyelid folds are beginning to form over the eyes.",
	46: "The baby is making their first (involuntary) movements, though you won't feel them for a while.",
	47: "Reminder: Stay hydrated! It's important for you and the developing baby.",
	48: "The liver is busy making red blood cells.",
	49: "Week 7! Your baby is looking more and more like a tiny human.",
	50: "Elbows are forming, allowing the arms to bend.",
	51: "The buds that will become teeth are forming inside the gums.",
	52: "Fun fact: The baby is generating about 100 new brain cells every minute!",
	53: "The intestines are developing, and for now, they are partly inside the umbilical cord.",
	54: "Feeling tired? Your body is working overtime building a whole new person!",
	55: "Your baby is now the size of a blueberry.",
	56: "All of the essential organs have begun to form. A major milestone!",
	57: "The 'tail' your baby had is almost gone.",
	58: "Fingers and toes are now more defined, though still slightly webbed.",
	59: "The baby's movements are becoming more coordinated.",
	60: "Reminder: Schedule your first prenatal appointment if you haven't already.",
	61: "The heart now has all four chambers.",
	62: "The baby is now officially called a 'fetus', which is Latin for 'offspring'.",
	63: "End of week 9. The most critical period of development is drawing to a close.",
	64: "Nails are beginning to form on those tiny fingers and toes.",
	65: "The fetus can now hiccup, though it's too small for you to feel.",
	66: "The kidneys are in their final place and are starting to produce urine.",
	67: "Fun fact: If you're having a boy, his testes will start producing testosterone this week.",
	68: "The baby's head is about half the length of the entire body.",
	69: "The intestines are moving from the umbilical cord into the abdomen.",
	70: "Week 10 is complete! Your baby is about the size of a prune.",
	71: "The fetus is practicing swallowing amniotic fluid.",
	72: "Tooth buds for permanent teeth are now forming behind the baby teeth buds.",
	73: "Fingerprints, unique to your baby, are starting to form on their fingertips.",
	74: "The baby is kicking and stretching, a little acrobat in the making.",
	75: "Reminder: Your sense of smell might be heightened. Stay away from strong odours if they bother you.",
	76: "The external ears are now fully formed and in their final position.",
	77: "Week 11! The baby is now the size of a fig.",
	78: "The irises of the eyes have begun to develop.",
	79: "The placenta is now producing most of the hormones needed to sustain the pregnancy.",
	80: "The baby's vocal cords are forming this week. The first step towards their first cry.",
	81: "The baby's bone marrow is starting to take over production of red blood cells.",
	82: "Movement is becoming more fluid as muscles and nerves connect.",
	83: "Fun fact: The baby can now open and close its hands into fists.",
	84: "Welcome to the second trimester! Many find this is the most comfortable phase.",
	85: "The risk of miscarriage drops significantly from this week on.",
	86: "The roof of the baby's mouth is now fully formed.",
	87: "Baby can now make facial expressions, like frowning and squinting.",
	88: "Reminder: You might be feeling a surge of energy. Enjoy it!",
	89: "Fine hair called lanugo is starting to cover the baby's body.",
	90: "Your baby is now about the size of a lemon.",
	91: "The neck is getting longer, and the chin is no longer resting on the chest.",
	92: "The baby's liver and pancreas are starting to function.",
	93: "You might start to show a small baby bump around this time.",
	94: "Fun fact: The baby is practicing breathing movements, though they are only taking in amniotic fluid.",
	95: "The baby's own unique fingerprints are now set.",
	96: "The ears are in their final position on the side of the head.",
	97: "Week 14 is done! The baby is about the size of a peach.",
	98: "The baby's skeleton is hardening from soft cartilage to bone, a process called ossification.",
	99: "The baby can now sense light. If you shine a flashlight on your belly, they might move away from it.",
	100: "The scalp hair pattern is being established.",
	101: "The baby's legs are now longer than their arms.",
	102: "Reminder: Start thinking about a baby registry, if you're planning one. It can be fun!",
	103: "The eyes are moving into their forward-facing position.",
	104: "Your baby is about the size of an apple.",
	105: "You might feel the first flutters of movement, called 'quickening'. It can feel like bubbles or a gentle twitch.",
	106: "The baby's taste buds are developing.",
	107: "The heart is now pumping about 25 quarts of blood a day.",
	108: "Fun fact: The gender of the baby might be visible on an ultrasound from this week on.",
	109: "The baby's circulatory system is fully operational.",
	110: "The toenails are starting to grow.",
	111: "Week 16! Your baby is now the size of an avocado.",
	112: "The baby's ears are in their final position and hearing is developing.",
	113: "Talk or sing to your baby! They may be able to hear you.",
	114: "Myelin, a protective coating, is beginning to form around the nerves.",
	115: "The baby's skeleton is hardening, so it's a good time to ensure you're getting enough calcium.",
	116: "Reminder: Your body is changing. Be kind to yourself and rest when you need to.",
	117: "The placenta is growing to keep up with the baby's needs.",
	118: "Your baby is about the size of a turnip.",
	119: "The baby is covered in a waxy substance called vernix caseosa, which protects their skin.",
	120: "Those kicks are getting stronger. Partners might be able to feel them soon!",
	121: "Fun fact: Babies are born with about 300 bones, which later fuse to become the 206 bones of an adult skeleton.",
	122: "The part of the brain responsible for senses (touch, taste, smell, sight, hearing) is developing.",
	123: "The baby has regular sleep and wake cycles.",
	124: "The baby's digestive system is practicing, swallowing amniotic fluid.",
	125: "Week 18 is over! Your baby is the size of a bell pepper.",
	126: "The mid-pregnancy anatomy scan is often scheduled around this time. You'll get to see your baby in detail!",
	127: "This scan checks on the baby's growth and the health of all their organs.",
	128: "It's a big day for many parents, seeing their little one on the screen.",
	129: "The baby's skin is still thin and translucent.",
	130: "Reminder: Start sleeping on your side if you haven't already. It's better for circulation.",
	131: "The baby's permanent teeth buds are now forming behind the baby teeth buds.",
	132: "You're at the halfway point! 20 weeks down, 20 to go.",
	133: "The baby is now covered in fine, downy hair called lanugo.",
	134: "You can now officially measure your pregnancy in months - you're 5 months pregnant!",
	135: "Fun fact: The baby can now hear and recognize your voice.",
	136: "The baby is practicing swallowing, which is good practice for the digestive system.",
	137: "The baby's eyebrows and eyelids are now present.",
	138: "If you're having a girl, her uterus and vagina are now in place.",
	139: "Week 21! Your baby is the size of a large banana.",
	140: "The bone marrow is now the primary site of red blood cell production.",
	141: "The baby's movements are changing from flutters to full-on kicks and punches.",
	142: "Your baby's taste buds are now developed enough to taste what you're eating through the amniotic fluid.",
	143: "Eat a varied diet - your baby might develop a taste for it!",
	144: "Reminder: It's normal to feel a bit forgetful. 'Pregnancy brain' is real!",
	145: "The baby can now open and close its eyes, though there's not much to see in there.",
	146: "Your baby is about the size of a carrot.",
	147: "The lungs are developing surfactant, a substance that will help them breathe air after birth.",
	148: "The baby's hearing is well-established. They can hear your heartbeat, your voice, and sounds from the outside world.",
	149: "Play music for your baby! See if you can feel a reaction.",
	150: "The baby's brain is growing incredibly fast.",
	151: "Fun fact: The baby's startle reflex is now developing.",
	152: "The baby's skin is becoming less translucent and more opaque.",
	153: "Week 23! Your baby is the size of a large mango.",
	154: "The baby is now considered 'viable', meaning they could potentially survive outside the womb with intensive medical care.",
	155: "The lungs are developing branches and the cells that produce surfactant.",
	156: "The baby's footprint is now about 1.5 inches long.",
	157: "The baby is gaining weight steadily, adding layers of fat.",
	158: "Reminder: Your growing belly might be causing some backaches. A warm bath can help.",
	159: "The baby's sense of balance is now active. They know which way is up!",
	160: "Your baby is about the size of an ear of corn.",
	161: "The baby's brainwaves are similar to those of a newborn.",
	162: "The baby is practicing breathing by inhaling and exhaling amniotic fluid.",
	163: "The nostrils, which have been plugged, are now opening up.",
	164: "Fun fact: The baby can now make a fist.",
	165: "The baby's eyes are forming and can perceive light.",
	166: "The baby's skin is still wrinkly, but fat stores are starting to plump it up.",
	167: "Week 25! Your baby is the size of a head of cauliflower.",
	168: "Welcome to the third trimester! The final stretch.",
	169: "Your baby's nervous system is maturing rapidly.",
	170: "The baby can open and close their eyes and may blink.",
	171: "The eyelashes have now formed.",
	172: "Reminder: You might be feeling more tired again. Listen to your body and rest.",
	173: "The baby's immune system is getting a boost from you.",
	174: "Your baby is about the size of a large eggplant.",
	175: "The baby is practicing breathing, and you might feel rhythmic movements, which could be hiccups!",
	176: "These hiccups are a cute reminder that your baby is getting ready for the outside world.",
	177: "The baby can now taste sweet and sour.",
	178: "Fun fact: The amount of amniotic fluid will start to decrease as the baby gets bigger.",
	179: "The baby is adding fat, which will help regulate their body temperature after birth.",
	180: "The baby's head is growing to accommodate the developing brain.",
	181: "Week 28! Your baby is the size of a butternut squash.",
	182: "The baby's bones are fully developed, but still soft and pliable.",
	183: "The baby's movements are strong and you can probably see your belly move.",
	184: "It's a good time to start tracking fetal movements. Get to know your baby's patterns.",
	185: "The lanugo, the fine hair covering the body, is starting to disappear.",
	186: "Reminder: Your doctor may recommend a glucose test around this time to check for gestational diabetes.",
	187: "The baby's brain is developing the grooves and indentations of a mature brain.",
	188: "Your baby is about the size of a pineapple.",
	189: "The baby's pupils can now constrict and dilate in response to light.",
	190: "The baby can turn their head from side to side.",
	191: "Your baby is putting on about half a pound a week from now on.",
	192: "Fun fact: The baby's adrenal glands are producing hormones that will stimulate milk production.",
	193: "The baby is getting ready for a head-down position in preparation for birth.",
	194: "The baby's kicks might be feeling quite powerful now!",
	195: "Week 31! Your baby is the size of a coconut.",
	196: "The five senses are all functional. The baby is taking in information from their world.",
	197: "The baby is practicing breathing, swallowing, and sucking - all essential skills for a newborn.",
	198: "You might be experiencing Braxton Hicks contractions, which are practice contractions.",
	199: "The baby's lungs are one of the last major organs to mature.",
	200: "Reminder: Pack your hospital bag. It's good to be prepared!",
	201: "The baby can now regulate their own body temperature.",
	202: "Your baby is about the size of a head of lettuce.",
	203: "The baby is likely in a head-down position now, but can still change position.",
	204: "The baby's irises now have colour, but the final eye colour won't be determined until after birth.",
	205: "The baby's skin is becoming smooth and soft.",
	206: "Fun fact: The baby's fingernails have reached the tips of their fingers.",
	207: "The baby is gaining about an ounce a day.",
	208: "The vernix, the waxy coating on the skin, is getting thicker.",
	209: "Week 33! Your baby is the size of a durian.",
	210: "The baby's skull bones are not yet fused, which allows them to move and overlap during birth.",
	211: "Antibodies are passing from you to the baby, providing immunity for the first few months of life.",
	212: "The baby is sleeping most of the day, likely dreaming!",
	213: "The baby's digestive system is ready for its first meal.",
	214: "Reminder: Finalize your birth plan, but be prepared for it to change.",
	215: "The baby is getting more and more cramped in there!",
	216: "Your baby is about the size of a cantaloupe melon.",
	217: "The baby is considered 'early term'. The lungs are maturing rapidly.",
	218: "Most of the lanugo has been shed.",
	219: "The baby might 'drop' into your pelvis, which is called lightening. This can make breathing easier.",
	220: "Fun fact: The baby is urinating about a pint of urine a day into the amniotic fluid.",
	221: "The baby's reflexes are all in place.",
	222: "The baby is practicing sucking on their thumb, which helps develop the sucking reflex.",
	223: "Week 35! Your baby is the size of a honeydew melon.",
	224: "Your baby is gaining fat, which will make them look more like a newborn.",
	225: "The baby's hearing is fully mature.",
	226: "The intestines are accumulating meconium, the baby's first bowel movement.",
	227: "The baby's movements might feel less like kicks and more like rolls and stretches.",
	228: "Reminder: Get plenty of rest. The final weeks can be tiring.",
	229: "The baby is getting ready for their journey into the world.",
	230: "Your baby is about the size of a bunch of Swiss chard.",
	231: "Your baby is now considered 'full term'! They are ready to be born anytime.",
	232: "The baby is gaining about half a pound a week.",
	233: "The brain is still developing and will continue to do so for years after birth.",
	234: "The baby's grip is surprisingly strong.",
	235: "Fun fact: The baby's head is the same circumference as their abdomen right now.",
	236: "The baby's eye colour is likely blue or grey, but could change in the months after birth.",
	237: "Week 37! Your baby is the size of a winter melon.",
	238: "The baby is shedding the vernix and lanugo, which are mixing with the amniotic fluid.",
	239: "The baby's lungs are mature and ready to take their first breath.",
	240: "The baby is just waiting for the signal to start labour.",
	241: "You might be feeling a lot of pressure in your pelvis.",
	242: "Reminder: Keep an eye out for signs of labour, like contractions or your water breaking.",
	243: "The baby is getting their final dose of antibodies from you.",
	244: "Your baby is about the size of a stalk of rhubarb.",
	245: "At 39 weeks, the baby is fully developed and ready for life outside the womb.",
	246: "The baby's brain is still forming connections at a rapid pace.",
	247: "The baby's fat layers are continuing to build, which will help with temperature regulation.",
	248: "Fun fact: The average newborn weighs about 7.5 pounds.",
	249: "The baby is likely in the head-down position, ready for birth.",
	250: "Try to relax and enjoy these last few days (or weeks!) of pregnancy.",
	251: "Week 39! Your baby is the size of a small pumpkin.",
	252: "It's your due date! But only about 5% of babies are born on their due date.",
	253: "Don't worry if you go past your due date. It's very common.",
	254: "The baby is still growing and gaining weight.",
	255: "The placenta is still providing all the nutrients your baby needs.",
	256: "Reminder: Continue to monitor your baby's movements.",
	257: "The baby is waiting for the perfect time to make their entrance.",
	258: "Your baby is about the size of a watermelon.",
	259: "Your body knows what to do. Trust the process.",
	260: "You're in the home stretch. You've got this!",
	261: "Any day now! The anticipation is building.",
	262: "Fun fact: The longest recorded pregnancy was 375 days!",
	263: "Your doctor might discuss induction if you go too far past your due date.",
	264: "Rest up. You'll need your energy for labour and delivery.",
	265: "It's almost time to meet your baby!",
	266: "Soak in these last moments of pregnancy. It's a special time.",
	267: "Your baby is fully cooked and ready to come out!",
	268: "The waiting is the hardest part. Try to stay patient.",
	269: "Every twinge might make you wonder 'is this it?'.",
	270: "You've done an amazing job growing a whole human!",
	271: "The moment you meet your baby will be unforgettable.",
	272: "Your life is about to change in the most wonderful way.",
	273: "Soon you'll be holding your little one in your arms.",
	274: "Almost there. The end of one journey and the beginning of another.",
	275: "Thinking of you as you wait to meet your little one.",
	276: "The big day is coming soon!",
	277: "You are strong and capable. You were made for this.",
	278: "Sending you strength and positive vibes for your birth experience.",
	279: "The best things in life are worth waiting for.",
	280: "Congratulations! The adventure of parenthood is about to begin.",
};
