// Each nested array covers one completed gestational week, starting at 0 weeks.
// Keeping seven updates together makes their relationship to the due date explicit.
const weeklyPregnancyUpdates: ReadonlyArray<ReadonlyArray<string>> = [
	[
		"Pregnancy dating starts today, on the first day of the last menstrual period. Conception has not happened yet.",
		"The uterine lining is shedding as a new menstrual cycle begins.",
		"Hormone levels are low while the body starts preparing a new group of follicles.",
		"One follicle will usually become dominant later in the cycle and release an egg.",
		"The 40-week pregnancy clock includes about two weeks before conception usually occurs.",
		"The uterus will begin building a fresh lining ready for a possible pregnancy.",
		"Almost 1 week: this is still the pre-conception part of gestational dating.",
	],
	[
		"Week 1 begins. Pregnancy is being dated, although there is not an embryo yet.",
		"Follicles in an ovary are developing under the influence of changing hormones.",
		"Oestrogen usually begins to rise as the body moves towards ovulation.",
		"The uterine lining is rebuilding and becoming richer in blood vessels.",
		"The exact timing of ovulation differs from one cycle to another.",
		"Gestational age is designed to provide one consistent clock for the whole pregnancy.",
		"Almost 2 weeks: ovulation may be approaching, depending on the cycle.",
	],
	[
		"Week 2 begins. Ovulation and conception often happen around this part of the pregnancy calendar.",
		"Around ovulation, an ovary releases an egg into a fallopian tube.",
		"An egg can be fertilised for only a short time after ovulation.",
		"If sperm meets the egg, fertilisation usually happens in a fallopian tube.",
		"At fertilisation, genetic material from the egg and sperm combines in one cell.",
		"That first cell, called a zygote, begins dividing as it travels towards the uterus.",
		"Almost 3 weeks: conception timing can vary, so these early milestones are approximate.",
	],
	[
		"Week 3 begins. If conception occurred, the tiny cluster of dividing cells is travelling towards the uterus.",
		"The dividing cells form a fluid-filled structure called a blastocyst.",
		"The blastocyst may now be reaching the uterus and preparing to implant.",
		"Implantation usually begins several days after fertilisation, but timing varies.",
		"Cells are already separating into groups that will form the embryo and placenta.",
		"After implantation starts, the body begins producing the pregnancy hormone hCG.",
		"Almost 4 weeks: the embryo is still microscopic, and many people do not yet know they are pregnant.",
	],
	[
		"Week 4 begins. A home pregnancy test may now detect hCG around the time a period is due.",
		"The embryo is tiny, and its cells are organising into layers that will form every part of the body.",
		"The neural tube, which will become the brain and spinal cord, is beginning to form.",
		"A simple heart tube and the earliest blood vessels are starting to develop.",
		"The amniotic sac, yolk sac and early placenta are supporting rapid development.",
		"The placenta is beginning the long process of establishing circulation with the uterus.",
		"Almost 5 weeks: the foundations of the brain, spine, heart and other organs are being laid down.",
	],
	[
		"Week 5 begins. The embryo is only a few millimetres long, but development is moving quickly.",
		"The brain and spinal cord are forming along the closing neural tube.",
		"The primitive heart tube is developing and may begin rhythmic cardiac activity around this time.",
		"Early structures for the eyes and ears are beginning to appear.",
		"Small buds that will become the arms and legs are starting to form.",
		"The placenta and umbilical connection are developing to exchange oxygen and nutrients.",
		"Almost 6 weeks: the main body plan is taking shape even though the embryo is still very small.",
	],
	[
		"Week 6 begins. The embryo is curved, with a proportionally large head and a rapidly developing brain.",
		"Arm and leg buds are becoming more noticeable.",
		"Tiny structures that will become the eyes, ears and mouth are developing.",
		"Cardiac activity can often be seen on an ultrasound around this stage, although timing varies.",
		"The neural tube is closing as the brain and spinal cord continue to develop.",
		"The liver, kidneys and digestive system are beginning their early development.",
		"Almost 7 weeks: growth is rapid, and the embryo is becoming more recognisably shaped.",
	],
	[
		"Week 7 begins. The brain is growing quickly and becoming more complex.",
		"The face is taking shape, with developing eyelids, nostrils and a small mouth.",
		"The arms are lengthening, and early elbows are beginning to form.",
		"Hands and feet look like small paddles as fingers and toes start forming inside them.",
		"The heart and circulation are becoming more organised.",
		"The umbilical cord is now a clear connection between the embryo and placenta.",
		"Almost 8 weeks: the major internal organs are present in early form and continue to mature.",
	],
	[
		"Week 8 begins. By the end of this week, the embryo is commonly around 13 to 16 millimetres long.",
		"Fingers and toes are becoming more distinct, although they may still be partly webbed.",
		"The upper lip, nose and eyelids are becoming easier to recognise.",
		"The arms can bend at the elbows, and the legs are lengthening.",
		"The heart, brain, stomach and intestines are all developing rapidly.",
		"Small spontaneous movements can begin, but they are far too gentle to be felt.",
		"Almost 9 weeks: the embryonic stage is ending and the fetal stage is about to begin.",
	],
	[
		"Week 9 begins. From around now, the developing baby is called a fetus rather than an embryo.",
		"The head is still large compared with the body because the brain is growing so quickly.",
		"The fingers and toes are separating and the wrists can bend.",
		"Facial features are becoming clearer as the eyes and ears move towards their usual positions.",
		"Muscles and nerves are connecting, allowing small movements.",
		"The placenta is taking on more of the work of supporting the pregnancy.",
		"Almost 10 weeks: every major organ has started forming, with a great deal of growth still ahead.",
	],
	[
		"Week 10 begins. The fetal period is focused on growth and the continuing maturation of organs.",
		"The forehead looks prominent while the brain continues its rapid development.",
		"Tiny tooth buds are forming beneath the gums.",
		"The elbows, knees, wrists and ankles are becoming more flexible.",
		"Fingers and toes are now more clearly separated, and small nails will soon begin forming.",
		"The kidneys are developing and the digestive organs are moving into position.",
		"Almost 11 weeks: movements are becoming more coordinated, even though they cannot yet be felt.",
	],
	[
		"Week 11 begins. The fetus can stretch, roll and make small movements inside the amniotic sac.",
		"The hands can open and close, and the fingers are growing tiny nail beds.",
		"The face is broad, with eyes set apart and ears still moving into position.",
		"The diaphragm is developing as the chest and abdomen become more defined.",
		"The kidneys are beginning to make urine, which becomes part of the amniotic fluid.",
		"External sex organs are developing, though they may not yet be clear on an ultrasound.",
		"Almost 12 weeks: the body is lengthening and becoming more proportionate.",
	],
	[
		"Week 12 begins. The organs, limbs, bones and muscles are all in place and will keep maturing.",
		"The fetus can curl fingers and toes and make reflex movements.",
		"The digestive and urinary systems are working at an early level.",
		"The liver is making blood cells while bone marrow continues to develop.",
		"The placenta is now the main source of oxygen and nutrients from the pregnant person's circulation.",
		"The heartbeat may be heard with a handheld Doppler, although position and timing can affect this.",
		"Almost 13 weeks: the first trimester is nearing its final week.",
	],
	[
		"Week 13 begins. This is the final week of the first trimester in standard obstetric dating.",
		"The body is starting to catch up with the head in size.",
		"The bones are hardening, especially in the skull and long bones.",
		"Fine fingerprints are developing on the fingertips.",
		"The fetus is swallowing amniotic fluid and the kidneys are producing urine.",
		"Movements are active but may still be too small to notice.",
		"Almost 14 weeks: the second trimester is about to begin.",
	],
	[
		"Week 14 begins, marking the start of the second trimester.",
		"The face is becoming more expressive as small facial muscles develop.",
		"The neck is more defined, and the head is sitting more upright.",
		"The arms and legs are lengthening while the joints move freely.",
		"The kidneys continue making urine and the fetus continues swallowing amniotic fluid.",
		"A fine layer of hair called lanugo will begin helping to protect the skin.",
		"Almost 15 weeks: growth is accelerating as the body becomes more proportionate.",
	],
	[
		"Week 15 begins. The skeleton is continuing to harden from cartilage into bone.",
		"The legs are now growing longer than the arms.",
		"The ears are moving into their final position on the sides of the head.",
		"Hearing structures are developing, and the fetus may begin responding to vibration and sound.",
		"The scalp hair pattern is forming, even if little hair grows before birth.",
		"Sucking and swallowing movements are being practised.",
		"Almost 16 weeks: movement is increasing, and the first flutters may be felt soon.",
	],
	[
		"Week 16 begins. Some people start to feel movement now, while others do not until later.",
		"The facial muscles can produce small expressions, although they are not intentional.",
		"The eyes can move slowly even though the eyelids remain closed.",
		"Muscles are getting stronger and limb movements are becoming more coordinated.",
		"The skeleton is visible on ultrasound as more bone tissue develops.",
		"The umbilical cord continues carrying oxygen and nutrients between the placenta and fetus.",
		"Almost 17 weeks: movement may feel like bubbles, flutters or a gentle tap.",
	],
	[
		"Week 17 begins. Fat stores are starting to form beneath the skin.",
		"The umbilical cord is growing thicker and stronger as demand increases.",
		"Hearing continues to develop, and sounds from inside the body are part of the fetal environment.",
		"The fingers can grasp, and the arms and legs are moving frequently.",
		"The lungs are developing branching airways, although they are not ready to breathe air.",
		"The nervous system is making more connections with muscles throughout the body.",
		"Almost 18 weeks: quickening may become easier to recognise over the coming weeks.",
	],
	[
		"Week 18 begins. Many people first notice fetal movement around this stage or in the next few weeks.",
		"The ears are well formed and hearing is becoming more useful.",
		"A protective coating called myelin is beginning to form around some nerves.",
		"The arms and legs now have the expected bones and joints, which continue to harden.",
		"The digestive system is practising by swallowing small amounts of amniotic fluid.",
		"The mid-pregnancy anatomy ultrasound is commonly offered between about 18 and 22 weeks.",
		"Almost 19 weeks: the fetus is active, with stretches, turns and small kicks.",
	],
	[
		"Week 19 begins. Hearing has developed enough for the fetus to experience sounds from outside the body.",
		"A waxy coating called vernix caseosa is forming to protect the skin in amniotic fluid.",
		"Lanugo helps the vernix stay on the skin.",
		"Eyebrows and scalp hair are becoming more visible.",
		"Sleep and wake patterns are starting to become more distinct.",
		"Sensory areas of the brain continue developing for touch, taste, hearing, sight and smell.",
		"Almost 20 weeks: the halfway point of a 40-week pregnancy is close.",
	],
	[
		"Week 20 begins. This is the halfway point in a pregnancy dated to 40 weeks.",
		"Movement is becoming stronger and may now be easier to recognise.",
		"The fetus swallows amniotic fluid and the kidneys return urine to the fluid around them.",
		"Hearing continues to improve, including familiar internal sounds such as the heartbeat.",
		"The anatomy scan can check growth and the development of major structures around this stage.",
		"The skin remains thin, with vernix and lanugo providing protection.",
		"Almost 21 weeks: there is still plenty of room for turns, kicks and stretches.",
	],
	[
		"Week 21 begins. The fetus is growing quickly and movements are becoming more purposeful.",
		"Bone marrow is becoming increasingly important for making blood cells.",
		"Taste buds are developing as small amounts of amniotic fluid are swallowed.",
		"The eyebrows and eyelids are becoming more defined.",
		"Vernix and lanugo continue protecting the delicate skin.",
		"Regular periods of activity and rest may be starting to emerge.",
		"Almost 22 weeks: kicks and rolls may now be strong enough for someone else to feel.",
	],
	[
		"Week 22 begins. The body is becoming more proportionate and increasingly newborn-like.",
		"The eyelids, eyebrows and lips are well defined.",
		"The hands can grip, and tiny fingernails continue to grow.",
		"The lungs are developing airways and cells needed for later breathing.",
		"The fetus can hear voices, the heartbeat and other sounds around them.",
		"Braxton Hicks tightenings may begin around this time for some people.",
		"Almost 23 weeks: weight gain will become an increasingly important part of development.",
	],
	[
		"Week 23 begins. The fetus is practising breathing movements using amniotic fluid.",
		"The lungs are building the fine branches and air sacs needed after birth.",
		"Movement may respond to familiar sounds or pressure on the abdomen.",
		"The sense of balance is developing in the inner ear.",
		"The skin is still thin and wrinkled because fat stores are only beginning to build.",
		"Sleep periods are becoming longer, mixed with active stretches and kicks.",
		"Almost 24 weeks: rapid growth and organ maturation continue together.",
	],
	[
		"Week 24 begins. The fetus is growing rapidly and movements are usually becoming stronger.",
		"Light and sound can prompt a change in movement or heart rate.",
		"The lungs are starting to produce small amounts of surfactant, which will help the air sacs stay open later.",
		"The inner ear is developed enough to help with balance and orientation.",
		"The face is well formed, with eyelashes, eyebrows and hair continuing to grow.",
		"Periods of sleep and activity may feel more predictable.",
		"Almost 25 weeks: the body will keep adding muscle and fat over the weeks ahead.",
	],
	[
		"Week 25 begins. The fetus is adding muscle and starting to build more fat beneath the skin.",
		"Reflexes are becoming stronger as the nervous system matures.",
		"Hearing is well established, and familiar voices are part of the soundscape.",
		"Hands can make a fist and may reach towards the face or umbilical cord.",
		"The lungs are still developing their air sacs and blood supply.",
		"Movement can include kicks, rolls, stretches and small rhythmic hiccups.",
		"Almost 26 weeks: growth is filling out a body that still looks lean.",
	],
	[
		"Week 26 begins. Fat and muscle are being added more quickly now.",
		"The eyelids may begin to open, allowing blinking to develop.",
		"The fetus can suck, hear, taste and respond to touch or sound.",
		"Brain activity is becoming more organised as nerve connections multiply.",
		"The lungs continue producing surfactant but still have significant maturing to do.",
		"Movements are often strong enough to change the shape of the abdomen briefly.",
		"Almost 27 weeks: the final week of the second trimester is approaching.",
	],
	[
		"Week 27 begins. This is the final week of the second trimester in standard obstetric dating.",
		"The brain is growing rapidly and developing more complex patterns of activity.",
		"The lungs, liver and immune system continue their steady maturation.",
		"The eyes can open and close, and eyelashes are present.",
		"Taste buds are active, and sucking movements are becoming more coordinated.",
		"Strong stretches, rolls and kicks can happen throughout periods of activity.",
		"Almost 28 weeks: the third trimester and its period of rapid weight gain are about to begin.",
	],
	[
		"Week 28 begins, marking the start of the third trimester.",
		"The eyes can open, close and respond to changes in light.",
		"The brain is developing the grooves and folds that increase its surface area.",
		"Fat stores are growing and making the skin look less wrinkled.",
		"Breathing movements, swallowing and sucking are all being practised.",
		"Sleep may include active periods that resemble the rapid-eye-movement stage.",
		"Almost 29 weeks: movements should continue as the available space gradually becomes tighter.",
	],
	[
		"Week 29 begins. The fetus is often around 1 kilogram now, although healthy growth varies.",
		"The brain and nervous system are increasingly able to coordinate body functions.",
		"Bones are developed but remain flexible and continue storing minerals.",
		"The lungs keep maturing while breathing practice strengthens the chest muscles.",
		"More fat is smoothing the skin and helping prepare for temperature control after birth.",
		"Kicks, stretches and rolls may feel powerful as muscles strengthen.",
		"Almost 30 weeks: the focus is increasingly on growth, brain development and organ maturation.",
	],
	[
		"Week 30 begins. Reflexes are developing, and the fetus may suck a thumb or fingers.",
		"The eyes can track light and the pupils can begin responding to brightness.",
		"Bone marrow is now taking the main role in producing red blood cells.",
		"The lungs continue developing surfactant and the network needed for gas exchange.",
		"Lanugo may start thinning as more fat accumulates beneath the skin.",
		"The brain is growing quickly and making billions of new connections.",
		"Almost 31 weeks: there is less room, so some movements may feel more like rolls than flips.",
	],
	[
		"Week 31 begins. The brain and central nervous system are taking more control of body functions.",
		"The lungs are still maturing, even as breathing movements become regular.",
		"Fat stores continue building and the arms and legs are becoming rounder.",
		"The fetus can turn the head and move all four limbs strongly.",
		"Long sleep periods alternate with recognisable active periods.",
		"The senses can process light, sound, taste and touch from inside the uterus.",
		"Almost 32 weeks: growth continues even as space for large movements decreases.",
	],
	[
		"Week 32 begins. There is less room now, but regular movement should continue.",
		"Fingernails have reached the fingertips, and toenails are continuing to grow.",
		"The skin is becoming smoother as more fat is stored underneath it.",
		"The bones are formed but remain soft and flexible, especially in the skull.",
		"Breathing, sucking and swallowing are being rehearsed for life after birth.",
		"Many babies settle head-down around this stage, while others turn later.",
		"Almost 33 weeks: each day brings more weight gain and further lung and brain maturation.",
	],
	[
		"Week 33 begins. The brain and nervous system are well developed and still making new connections.",
		"Weight gain is helping the fetus look rounder and more like a newborn.",
		"The skull bones stay flexible and are not fused, which leaves room for brain growth and birth.",
		"Antibodies are passing across the placenta and contributing to early immune protection.",
		"The pupils can change size in response to light reaching the uterus.",
		"Lanugo is beginning to disappear while the protective vernix remains on the skin.",
		"Nearly 34 weeks: there is less room now, but movements should continue in the baby's usual pattern.",
	],
	[
		"Week 34 begins. The fetus is often around 45 centimetres from head to heel, with plenty of individual variation.",
		"The body is curled into a compact position as space in the uterus becomes tighter.",
		"Fat is filling out the limbs and helping the skin become smooth.",
		"The lungs and brain are still maturing despite looking increasingly ready for birth.",
		"Kicks and rolls may feel different now, but the usual movement pattern remains important.",
		"The immune system is benefiting from antibodies transferred through the placenta.",
		"Almost 35 weeks: most development now centres on growth and the final maturation of organs.",
	],
	[
		"Week 35 begins. The fetus is continuing to gain fat and develop a rounder newborn shape.",
		"The kidneys are developed, and the liver can process some waste products.",
		"Hearing is mature enough to recognise familiar voices and rhythms.",
		"The brain and lungs still have important development to complete before the due date.",
		"Space is tight, so movements may feel more like stretches and rolls than sharp kicks.",
		"Braxton Hicks tightenings can become more noticeable as the body prepares for birth.",
		"Almost 36 weeks: the fetus is building reserves and practising the skills needed after birth.",
	],
	[
		"Week 36 begins. The fetus is often around 2.5 kilograms, although healthy size varies widely.",
		"The body is curled and compact, with the knees bent towards the chest.",
		"Many babies are head-down by now, but position differs from one pregnancy to another.",
		"The lungs are close to maturity and continue making surfactant.",
		"Sucking and swallowing are becoming coordinated in preparation for feeding.",
		"Some lanugo and vernix remain, continuing to protect the skin.",
		"Almost 37 weeks: the early-term period is about to begin, but growth and maturation continue.",
	],
	[
		"Week 37 begins. This is early term, not full term, and the brain, lungs and liver are still maturing.",
		"Fat continues to build and support temperature control after birth.",
		"The hands have a firm grasp and sucking movements are well practised.",
		"Most lanugo has gone, while some vernix may remain in skin folds.",
		"The head may move deeper into the pelvis, although this can happen earlier or later.",
		"Labour can begin before the due date, but the exact timing cannot be predicted.",
		"Almost 38 weeks: regular movement remains expected even with very little room.",
	],
	[
		"Week 38 begins. The pregnancy is still early term through 38 weeks and 6 days.",
		"The organs are working together and continuing their final preparation for birth.",
		"Weight and fat stores can keep increasing, though the rate differs for every baby.",
		"The intestines contain meconium, which will become the first bowel movement after birth.",
		"The placenta and umbilical cord continue supplying oxygen and nutrients until birth.",
		"Rolls, stretches and smaller kicks should continue as part of the usual movement pattern.",
		"Almost 39 weeks: the full-term period is about to begin.",
	],
	[
		"Week 39 begins. This is the start of the full-term period.",
		"The baby is ready for birth, while the brain and lungs continue developing every day.",
		"Weight gain may slow, but fat stores can still increase before labour begins.",
		"The chest keeps practising breathing movements even though oxygen still comes through the placenta.",
		"Vernix may remain in skin creases and continue protecting the skin.",
		"The usual pattern of movement should continue right up to and during labour.",
		"Almost 40 weeks: the estimated due date is tomorrow, but it is only an estimate.",
	],
	[
		"Today is the estimated due date: 40 weeks and 0 days. Only about 1 in 20 babies arrives on the exact due date.",
	],
];

export const pregnancyDayUpdate = weeklyPregnancyUpdates.reduce<
	Record<number, string>
>((updates, weekUpdates, week) => {
	for (const [dayOfWeek, update] of weekUpdates.entries()) {
		updates[week * 7 + dayOfWeek] = update;
	}

	return updates;
}, {});
